#define GEOM13_C

#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include <gsl/gsl_complex.h>
#include <gsl/gsl_complex_math.h>
#include <gsl/gsl_matrix_complex_double.h>
#include <gsl/gsl_blas.h>
#include "geom.h"
#include "dirac.h"
#include "matop.h"
#include "global.h"

// TYPE (1,3) GEOMETRY

void geom_check13()
{
    if(nH != 2 || nL != 6)
    {
        printf("Error: geometry is not (1,3)\n");
        exit(EXIT_FAILURE);
    }
}

// build gamma matrices
void init_gamma13()
{
    
    for(int i=0; i<nH; i++)
            gammaH[i] = gsl_matrix_complex_calloc(dimG, dimG);
        for(int i=0; i<nL; i++)
            gammaL[i] = gsl_matrix_complex_calloc(dimG, dimG);


    // gamma H0
    gsl_matrix_complex_set(gammaH[0], 0, 2, gsl_complex_rect(1., 0.));
    gsl_matrix_complex_set(gammaH[0], 1, 3, gsl_complex_rect(1., 0.));
    gsl_matrix_complex_set(gammaH[0], 2, 0, gsl_complex_rect(1., 0.));
    gsl_matrix_complex_set(gammaH[0], 3, 1, gsl_complex_rect(1., 0.));

    // gamma H1
    gsl_matrix_complex_set(gammaH[1], 0, 2, gsl_complex_rect(0., 1.));
    gsl_matrix_complex_set(gammaH[1], 1, 3, gsl_complex_rect(0., 1.));
    gsl_matrix_complex_set(gammaH[1], 2, 0, gsl_complex_rect(0., -1.));
    gsl_matrix_complex_set(gammaH[1], 3, 1, gsl_complex_rect(0., -1.));

    // gamma L0
    gsl_matrix_complex_set(gammaL[0], 0, 3, gsl_complex_rect(-1., 0.));
    gsl_matrix_complex_set(gammaL[0], 1, 2, gsl_complex_rect(-1., 0.));
    gsl_matrix_complex_set(gammaL[0], 2, 1, gsl_complex_rect(1., 0.));
    gsl_matrix_complex_set(gammaL[0], 3, 0, gsl_complex_rect(1., 0.));
    
    // gamma L1
    gsl_matrix_complex_set(gammaL[1], 0, 3, gsl_complex_rect(0., 1.));
    gsl_matrix_complex_set(gammaL[1], 1, 2, gsl_complex_rect(0., -1.));
    gsl_matrix_complex_set(gammaL[1], 2, 1, gsl_complex_rect(0., -1.));
    gsl_matrix_complex_set(gammaL[1], 3, 0, gsl_complex_rect(0., 1.));
    
    // gamma L2
    gsl_matrix_complex_set(gammaL[2], 0, 2, gsl_complex_rect(-1., 0.));
    gsl_matrix_complex_set(gammaL[2], 1, 3, gsl_complex_rect(1., 0.));
    gsl_matrix_complex_set(gammaL[2], 2, 0, gsl_complex_rect(1., 0.));
    gsl_matrix_complex_set(gammaL[2], 3, 1, gsl_complex_rect(-1., 0.));
    
    // gamma L3
    gsl_matrix_complex_set(gammaL[3], 0, 2, gsl_complex_rect(0., -1.));
    gsl_matrix_complex_set(gammaL[3], 1, 3, gsl_complex_rect(0., 1.));
    gsl_matrix_complex_set(gammaL[3], 2, 0, gsl_complex_rect(0., -1.));
    gsl_matrix_complex_set(gammaL[3], 3, 1, gsl_complex_rect(0., 1.));

    // gamma L4
    gsl_matrix_complex_set(gammaL[4], 0, 3, gsl_complex_rect(1., 0.));
    gsl_matrix_complex_set(gammaL[4], 1, 2, gsl_complex_rect(-1., 0.));
    gsl_matrix_complex_set(gammaL[4], 2, 1, gsl_complex_rect(1., 0.));
    gsl_matrix_complex_set(gammaL[4], 3, 0, gsl_complex_rect(-1., 0.));

    // gamma L5
    gsl_matrix_complex_set(gammaL[5], 0, 3, gsl_complex_rect(0., -1.));
    gsl_matrix_complex_set(gammaL[5], 1, 2, gsl_complex_rect(0., -1.));
    gsl_matrix_complex_set(gammaL[5], 2, 1, gsl_complex_rect(0., -1.));
    gsl_matrix_complex_set(gammaL[5], 3, 0, gsl_complex_rect(0., -1.));
}


void actionD2t13(double* vecS, int* control)
{
    gsl_matrix_complex* H0 = H[0];
    gsl_complex trH0 = trace(H0);
    gsl_matrix_complex* L0 = L[0];
    gsl_matrix_complex* L1 = L[1];
    gsl_matrix_complex* L2 = L[2];
    gsl_matrix_complex* L3 = L[3];
    gsl_matrix_complex* L4 = L[4];
    gsl_matrix_complex* L5 = L[5];
    gsl_matrix_complex* H1 = H[1];
    gsl_complex trH1 = trace(H1);
    gsl_matrix_complex* H0H0 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H0, H0, GSL_COMPLEX_ZERO, H0H0);
    gsl_complex trH0H0 = trace(H0H0);
    gsl_matrix_complex* L5L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L5, L5, GSL_COMPLEX_ZERO, L5L5);
    gsl_complex trL5L5 = trace(L5L5);
    gsl_matrix_complex* L0L0 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L0, L0, GSL_COMPLEX_ZERO, L0L0);
    gsl_complex trL0L0 = trace(L0L0);
    gsl_matrix_complex* L1L1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L1, L1, GSL_COMPLEX_ZERO, L1L1);
    gsl_complex trL1L1 = trace(L1L1);
    gsl_matrix_complex* H1H1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H1, H1, GSL_COMPLEX_ZERO, H1H1);
    gsl_complex trH1H1 = trace(H1H1);
    gsl_matrix_complex* L3L3 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L3, L3, GSL_COMPLEX_ZERO, L3L3);
    gsl_complex trL3L3 = trace(L3L3);
    gsl_matrix_complex* L2L2 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L2, L2, GSL_COMPLEX_ZERO, L2L2);
    gsl_complex trL2L2 = trace(L2L2);
    gsl_matrix_complex* L4L4 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L4, L4, GSL_COMPLEX_ZERO, L4L4);
    gsl_complex trL4L4 = trace(L4L4);
    gsl_matrix_complex_free(H0H0);
    gsl_matrix_complex_free(L5L5);
    gsl_matrix_complex_free(L0L0);
    gsl_matrix_complex_free(L1L1);
    gsl_matrix_complex_free(H1H1);
    gsl_matrix_complex_free(L3L3);
    gsl_matrix_complex_free(L2L2);
    gsl_matrix_complex_free(L4L4);
    if(control[0])
        vecS[0] = +8*dim*GSL_REAL(trH1H1)+8*dim*GSL_REAL(trL1L1)+8*GSL_REAL(gsl_complex_mul(trH0,trH0))+8*dim*GSL_REAL(trL2L2)+8*dim*GSL_REAL(trL5L5)+8*GSL_REAL(gsl_complex_mul(trH1,trH1))+8*dim*GSL_REAL(trL0L0)+8*dim*GSL_REAL(trL4L4)+8*dim*GSL_REAL(trL3L3)+8*dim*GSL_REAL(trH0H0);
    if(control[1])
        vecS[1] = +8*dim*GSL_IMAG(trH1H1)+8*dim*GSL_IMAG(trL1L1)+8*GSL_IMAG(gsl_complex_mul(trH0,trH0))+8*dim*GSL_IMAG(trL2L2)+8*dim*GSL_IMAG(trL5L5)+8*GSL_IMAG(gsl_complex_mul(trH1,trH1))+8*dim*GSL_IMAG(trL0L0)+8*dim*GSL_IMAG(trL4L4)+8*dim*GSL_IMAG(trL3L3)+8*dim*GSL_IMAG(trH0H0);
    if(control[2])
        vecS[2] = GSL_REAL(trH0);
    if(control[3])
        vecS[3] = GSL_REAL(trH0H0);
    if(control[4])
        vecS[4] = GSL_REAL(trH1);
    if(control[5])
        vecS[5] = GSL_REAL(trH1H1);
}

void actionD4D2t13(double* vecS, int* control)
{
    gsl_matrix_complex* H0 = H[0];
    gsl_complex trH0 = trace(H0);
    gsl_matrix_complex* L0 = L[0];
    gsl_matrix_complex* L1 = L[1];
    gsl_matrix_complex* L2 = L[2];
    gsl_matrix_complex* L3 = L[3];
    gsl_matrix_complex* L4 = L[4];
    gsl_matrix_complex* L5 = L[5];
    gsl_matrix_complex* H1 = H[1];
    gsl_complex trH1 = trace(H1);
    gsl_matrix_complex* L3L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L3, L5, GSL_COMPLEX_ZERO, L3L5);
    gsl_complex trL3L5 = trace(L3L5);
    gsl_matrix_complex* H0L1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H0, L1, GSL_COMPLEX_ZERO, H0L1);
    gsl_complex trH0L1 = trace(H0L1);
    gsl_matrix_complex* H0H0 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H0, H0, GSL_COMPLEX_ZERO, H0H0);
    gsl_complex trH0H0 = trace(H0H0);
    gsl_matrix_complex* L1L4 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L1, L4, GSL_COMPLEX_ZERO, L1L4);
    gsl_complex trL1L4 = trace(L1L4);
    gsl_matrix_complex* L1L2 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L1, L2, GSL_COMPLEX_ZERO, L1L2);
    gsl_complex trL1L2 = trace(L1L2);
    gsl_matrix_complex* H1L0 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H1, L0, GSL_COMPLEX_ZERO, H1L0);
    gsl_complex trH1L0 = trace(H1L0);
    gsl_matrix_complex* H1L3 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H1, L3, GSL_COMPLEX_ZERO, H1L3);
    gsl_complex trH1L3 = trace(H1L3);
    gsl_matrix_complex* L2L4 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L2, L4, GSL_COMPLEX_ZERO, L2L4);
    gsl_complex trL2L4 = trace(L2L4);
    gsl_matrix_complex* L3L4 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L3, L4, GSL_COMPLEX_ZERO, L3L4);
    gsl_complex trL3L4 = trace(L3L4);
    gsl_matrix_complex* L1L3 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L1, L3, GSL_COMPLEX_ZERO, L1L3);
    gsl_complex trL1L3 = trace(L1L3);
    gsl_matrix_complex* L0L1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L0, L1, GSL_COMPLEX_ZERO, L0L1);
    gsl_complex trL0L1 = trace(L0L1);
    gsl_matrix_complex* L1L1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L1, L1, GSL_COMPLEX_ZERO, L1L1);
    gsl_complex trL1L1 = trace(L1L1);
    gsl_matrix_complex* L0L3 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L0, L3, GSL_COMPLEX_ZERO, L0L3);
    gsl_complex trL0L3 = trace(L0L3);
    gsl_matrix_complex* L2L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L2, L5, GSL_COMPLEX_ZERO, L2L5);
    gsl_complex trL2L5 = trace(L2L5);
    gsl_matrix_complex* L4L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L4, L5, GSL_COMPLEX_ZERO, L4L5);
    gsl_complex trL4L5 = trace(L4L5);
    gsl_matrix_complex* L2L3 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L2, L3, GSL_COMPLEX_ZERO, L2L3);
    gsl_complex trL2L3 = trace(L2L3);
    gsl_matrix_complex* L0L4 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L0, L4, GSL_COMPLEX_ZERO, L0L4);
    gsl_complex trL0L4 = trace(L0L4);
    gsl_matrix_complex* H0L3 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H0, L3, GSL_COMPLEX_ZERO, H0L3);
    gsl_complex trH0L3 = trace(H0L3);
    gsl_matrix_complex* H1L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H1, L5, GSL_COMPLEX_ZERO, H1L5);
    gsl_complex trH1L5 = trace(H1L5);
    gsl_matrix_complex* H0L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H0, L5, GSL_COMPLEX_ZERO, H0L5);
    gsl_complex trH0L5 = trace(H0L5);
    gsl_matrix_complex* L0L2 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L0, L2, GSL_COMPLEX_ZERO, L0L2);
    gsl_complex trL0L2 = trace(L0L2);
    gsl_matrix_complex* L4L4 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L4, L4, GSL_COMPLEX_ZERO, L4L4);
    gsl_complex trL4L4 = trace(L4L4);
    gsl_matrix_complex* L3L3 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L3, L3, GSL_COMPLEX_ZERO, L3L3);
    gsl_complex trL3L3 = trace(L3L3);
    gsl_matrix_complex* L0L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L0, L5, GSL_COMPLEX_ZERO, L0L5);
    gsl_complex trL0L5 = trace(L0L5);
    gsl_matrix_complex* L5L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L5, L5, GSL_COMPLEX_ZERO, L5L5);
    gsl_complex trL5L5 = trace(L5L5);
    gsl_matrix_complex* H0L4 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H0, L4, GSL_COMPLEX_ZERO, H0L4);
    gsl_complex trH0L4 = trace(H0L4);
    gsl_matrix_complex* H1L4 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H1, L4, GSL_COMPLEX_ZERO, H1L4);
    gsl_complex trH1L4 = trace(H1L4);
    gsl_matrix_complex* L0L0 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L0, L0, GSL_COMPLEX_ZERO, L0L0);
    gsl_complex trL0L0 = trace(L0L0);
    gsl_matrix_complex* L2L2 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L2, L2, GSL_COMPLEX_ZERO, L2L2);
    gsl_complex trL2L2 = trace(L2L2);
    gsl_matrix_complex* H1L2 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H1, L2, GSL_COMPLEX_ZERO, H1L2);
    gsl_complex trH1L2 = trace(H1L2);
    gsl_matrix_complex* H0H1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H0, H1, GSL_COMPLEX_ZERO, H0H1);
    gsl_complex trH0H1 = trace(H0H1);
    gsl_matrix_complex* H0L2 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H0, L2, GSL_COMPLEX_ZERO, H0L2);
    gsl_complex trH0L2 = trace(H0L2);
    gsl_matrix_complex* H1L1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H1, L1, GSL_COMPLEX_ZERO, H1L1);
    gsl_complex trH1L1 = trace(H1L1);
    gsl_matrix_complex* H1H1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H1, H1, GSL_COMPLEX_ZERO, H1H1);
    gsl_complex trH1H1 = trace(H1H1);
    gsl_matrix_complex* H0L0 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H0, L0, GSL_COMPLEX_ZERO, H0L0);
    gsl_complex trH0L0 = trace(H0L0);
    gsl_matrix_complex* L1L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L1, L5, GSL_COMPLEX_ZERO, L1L5);
    gsl_complex trL1L5 = trace(L1L5);
    gsl_matrix_complex* L5L4 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L5, L4, GSL_COMPLEX_ZERO, L5L4);
    gsl_matrix_complex* L4H1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L4, H1, GSL_COMPLEX_ZERO, L4H1);
    gsl_matrix_complex* L4L1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L4, L1, GSL_COMPLEX_ZERO, L4L1);
    gsl_matrix_complex* L5L1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L5, L1, GSL_COMPLEX_ZERO, L5L1);
    gsl_matrix_complex* L5H1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L5, H1, GSL_COMPLEX_ZERO, L5H1);
    gsl_matrix_complex* L0H1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L0, H1, GSL_COMPLEX_ZERO, L0H1);
    gsl_matrix_complex* L5L3 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L5, L3, GSL_COMPLEX_ZERO, L5L3);
    gsl_matrix_complex* L2H1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L2, H1, GSL_COMPLEX_ZERO, L2H1);
    gsl_matrix_complex* L3H1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L3, H1, GSL_COMPLEX_ZERO, L3H1);
    gsl_matrix_complex* L4L2 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L4, L2, GSL_COMPLEX_ZERO, L4L2);
    gsl_matrix_complex* L3L2 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L3, L2, GSL_COMPLEX_ZERO, L3L2);
    gsl_matrix_complex* L2L1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L2, L1, GSL_COMPLEX_ZERO, L2L1);
    gsl_matrix_complex* L2L0 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L2, L0, GSL_COMPLEX_ZERO, L2L0);
    gsl_matrix_complex* L4L0 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L4, L0, GSL_COMPLEX_ZERO, L4L0);
    gsl_matrix_complex* L3L1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L3, L1, GSL_COMPLEX_ZERO, L3L1);
    gsl_matrix_complex* L1L0 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L1, L0, GSL_COMPLEX_ZERO, L1L0);
    gsl_matrix_complex* L5L2 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L5, L2, GSL_COMPLEX_ZERO, L5L2);
    gsl_matrix_complex* L5L0 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L5, L0, GSL_COMPLEX_ZERO, L5L0);
    gsl_matrix_complex* L1H1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L1, H1, GSL_COMPLEX_ZERO, L1H1);
    gsl_matrix_complex* L3L0 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L3, L0, GSL_COMPLEX_ZERO, L3L0);
    gsl_matrix_complex* L4L3 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L4, L3, GSL_COMPLEX_ZERO, L4L3);
    gsl_matrix_complex* L0L2L4 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L0, L2L4, GSL_COMPLEX_ZERO, L0L2L4);
    gsl_complex trL0L2L4 = trace(L0L2L4);
    gsl_matrix_complex* L3L5L4 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L3, L5L4, GSL_COMPLEX_ZERO, L3L5L4);
    gsl_complex trL3L5L4 = trace(L3L5L4);
    gsl_matrix_complex* L2L4L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L2, L4L5, GSL_COMPLEX_ZERO, L2L4L5);
    gsl_complex trL2L4L5 = trace(L2L4L5);
    gsl_matrix_complex* H0L1L4 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H0, L1L4, GSL_COMPLEX_ZERO, H0L1L4);
    gsl_complex trH0L1L4 = trace(H0L1L4);
    gsl_matrix_complex* L1L5L2 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L1, L5L2, GSL_COMPLEX_ZERO, L1L5L2);
    gsl_complex trL1L5L2 = trace(L1L5L2);
    gsl_matrix_complex* H1L1L4 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H1, L1L4, GSL_COMPLEX_ZERO, H1L1L4);
    gsl_complex trH1L1L4 = trace(H1L1L4);
    gsl_matrix_complex* H0L5L0 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H0, L5L0, GSL_COMPLEX_ZERO, H0L5L0);
    gsl_complex trH0L5L0 = trace(H0L5L0);
    gsl_matrix_complex* H0L4L1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H0, L4L1, GSL_COMPLEX_ZERO, H0L4L1);
    gsl_complex trH0L4L1 = trace(H0L4L1);
    gsl_matrix_complex* H1L0L0 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H1, L0L0, GSL_COMPLEX_ZERO, H1L0L0);
    gsl_complex trH1L0L0 = trace(H1L0L0);
    gsl_matrix_complex* L3L4L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L3, L4L5, GSL_COMPLEX_ZERO, L3L4L5);
    gsl_complex trL3L4L5 = trace(L3L4L5);
    gsl_matrix_complex* H0L0L0 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H0, L0L0, GSL_COMPLEX_ZERO, H0L0L0);
    gsl_complex trH0L0L0 = trace(H0L0L0);
    gsl_matrix_complex* H0L2L2 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H0, L2L2, GSL_COMPLEX_ZERO, H0L2L2);
    gsl_complex trH0L2L2 = trace(H0L2L2);
    gsl_matrix_complex* L0L2L1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L0, L2L1, GSL_COMPLEX_ZERO, L0L2L1);
    gsl_complex trL0L2L1 = trace(L0L2L1);
    gsl_matrix_complex* H0L2L3 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H0, L2L3, GSL_COMPLEX_ZERO, H0L2L3);
    gsl_complex trH0L2L3 = trace(H0L2L3);
    gsl_matrix_complex* L1L5L3 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L1, L5L3, GSL_COMPLEX_ZERO, L1L5L3);
    gsl_complex trL1L5L3 = trace(L1L5L3);
    gsl_matrix_complex* L0L3L1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L0, L3L1, GSL_COMPLEX_ZERO, L0L3L1);
    gsl_complex trL0L3L1 = trace(L0L3L1);
    gsl_matrix_complex* L1L2L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L1, L2L5, GSL_COMPLEX_ZERO, L1L2L5);
    gsl_complex trL1L2L5 = trace(L1L2L5);
    gsl_matrix_complex* L0L1L2 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L0, L1L2, GSL_COMPLEX_ZERO, L0L1L2);
    gsl_complex trL0L1L2 = trace(L0L1L2);
    gsl_matrix_complex* H1L2L3 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H1, L2L3, GSL_COMPLEX_ZERO, H1L2L3);
    gsl_complex trH1L2L3 = trace(H1L2L3);
    gsl_matrix_complex* H1L2L2 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H1, L2L2, GSL_COMPLEX_ZERO, H1L2L2);
    gsl_complex trH1L2L2 = trace(H1L2L2);
    gsl_matrix_complex* H1H1H1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H1, H1H1, GSL_COMPLEX_ZERO, H1H1H1);
    gsl_complex trH1H1H1 = trace(H1H1H1);
    gsl_matrix_complex* H0L4L4 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H0, L4L4, GSL_COMPLEX_ZERO, H0L4L4);
    gsl_complex trH0L4L4 = trace(H0L4L4);
    gsl_matrix_complex* H1L3L3 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H1, L3L3, GSL_COMPLEX_ZERO, H1L3L3);
    gsl_complex trH1L3L3 = trace(H1L3L3);
    gsl_matrix_complex* H0L1L1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H0, L1L1, GSL_COMPLEX_ZERO, H0L1L1);
    gsl_complex trH0L1L1 = trace(H0L1L1);
    gsl_matrix_complex* L1L3L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L1, L3L5, GSL_COMPLEX_ZERO, L1L3L5);
    gsl_complex trL1L3L5 = trace(L1L3L5);
    gsl_matrix_complex* H1L3L2 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H1, L3L2, GSL_COMPLEX_ZERO, H1L3L2);
    gsl_complex trH1L3L2 = trace(H1L3L2);
    gsl_matrix_complex* H1L5L0 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H1, L5L0, GSL_COMPLEX_ZERO, H1L5L0);
    gsl_complex trH1L5L0 = trace(H1L5L0);
    gsl_matrix_complex* H0H0H0 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H0, H0H0, GSL_COMPLEX_ZERO, H0H0H0);
    gsl_complex trH0H0H0 = trace(H0H0H0);
    gsl_matrix_complex* H0L3L3 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H0, L3L3, GSL_COMPLEX_ZERO, H0L3L3);
    gsl_complex trH0L3L3 = trace(H0L3L3);
    gsl_matrix_complex* H0H1H1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H0, H1H1, GSL_COMPLEX_ZERO, H0H1H1);
    gsl_complex trH0H1H1 = trace(H0H1H1);
    gsl_matrix_complex* H1L4L1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H1, L4L1, GSL_COMPLEX_ZERO, H1L4L1);
    gsl_complex trH1L4L1 = trace(H1L4L1);
    gsl_matrix_complex* H0L0L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H0, L0L5, GSL_COMPLEX_ZERO, H0L0L5);
    gsl_complex trH0L0L5 = trace(H0L0L5);
    gsl_matrix_complex* H1L5L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H1, L5L5, GSL_COMPLEX_ZERO, H1L5L5);
    gsl_complex trH1L5L5 = trace(H1L5L5);
    gsl_matrix_complex* L2L5L4 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L2, L5L4, GSL_COMPLEX_ZERO, L2L5L4);
    gsl_complex trL2L5L4 = trace(L2L5L4);
    gsl_matrix_complex* H0H0H1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H0, H0H1, GSL_COMPLEX_ZERO, H0H0H1);
    gsl_complex trH0H0H1 = trace(H0H0H1);
    gsl_matrix_complex* L0L4L3 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L0, L4L3, GSL_COMPLEX_ZERO, L0L4L3);
    gsl_complex trL0L4L3 = trace(L0L4L3);
    gsl_matrix_complex* H0L3L2 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H0, L3L2, GSL_COMPLEX_ZERO, H0L3L2);
    gsl_complex trH0L3L2 = trace(H0L3L2);
    gsl_matrix_complex* L0L4L2 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L0, L4L2, GSL_COMPLEX_ZERO, L0L4L2);
    gsl_complex trL0L4L2 = trace(L0L4L2);
    gsl_matrix_complex* H0L5L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H0, L5L5, GSL_COMPLEX_ZERO, H0L5L5);
    gsl_complex trH0L5L5 = trace(H0L5L5);
    gsl_matrix_complex* H1L0L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H1, L0L5, GSL_COMPLEX_ZERO, H1L0L5);
    gsl_complex trH1L0L5 = trace(H1L0L5);
    gsl_matrix_complex* L0L1L3 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L0, L1L3, GSL_COMPLEX_ZERO, L0L1L3);
    gsl_complex trL0L1L3 = trace(L0L1L3);
    gsl_matrix_complex* H1L1L1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H1, L1L1, GSL_COMPLEX_ZERO, H1L1L1);
    gsl_complex trH1L1L1 = trace(H1L1L1);
    gsl_matrix_complex* H1L4L4 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H1, L4L4, GSL_COMPLEX_ZERO, H1L4L4);
    gsl_complex trH1L4L4 = trace(H1L4L4);
    gsl_matrix_complex* L0L3L4 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L0, L3L4, GSL_COMPLEX_ZERO, L0L3L4);
    gsl_complex trL0L3L4 = trace(L0L3L4);
    gsl_matrix_complex* H1L4L2L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H1L4, L2L5, GSL_COMPLEX_ZERO, H1L4L2L5);
    gsl_complex trH1L4L2L5 = trace(H1L4L2L5);
    gsl_matrix_complex* H1H1L0L0 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H1H1, L0L0, GSL_COMPLEX_ZERO, H1H1L0L0);
    gsl_complex trH1H1L0L0 = trace(H1H1L0L0);
    gsl_matrix_complex* L2L2L3L3 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L2L2, L3L3, GSL_COMPLEX_ZERO, L2L2L3L3);
    gsl_complex trL2L2L3L3 = trace(L2L2L3L3);
    gsl_matrix_complex* H0L1L0L3 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0L1, L0L3, GSL_COMPLEX_ZERO, H0L1L0L3);
    gsl_complex trH0L1L0L3 = trace(H0L1L0L3);
    gsl_matrix_complex* L1L1L2L2 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L1L1, L2L2, GSL_COMPLEX_ZERO, L1L1L2L2);
    gsl_complex trL1L1L2L2 = trace(L1L1L2L2);
    gsl_matrix_complex* H1H1L1L1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H1H1, L1L1, GSL_COMPLEX_ZERO, H1H1L1L1);
    gsl_complex trH1H1L1L1 = trace(H1H1L1L1);
    gsl_matrix_complex* H1L1L0L2 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H1L1, L0L2, GSL_COMPLEX_ZERO, H1L1L0L2);
    gsl_complex trH1L1L0L2 = trace(H1L1L0L2);
    gsl_matrix_complex* H1H1L2L2 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H1H1, L2L2, GSL_COMPLEX_ZERO, H1H1L2L2);
    gsl_complex trH1H1L2L2 = trace(H1H1L2L2);
    gsl_matrix_complex* H0L5L2L1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0L5, L2L1, GSL_COMPLEX_ZERO, H0L5L2L1);
    gsl_complex trH0L5L2L1 = trace(H0L5L2L1);
    gsl_matrix_complex* L0L3L5L2 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, L0L3, L5L2, GSL_COMPLEX_ZERO, L0L3L5L2);
    gsl_complex trL0L3L5L2 = trace(L0L3L5L2);
    gsl_matrix_complex* H0L2L5L1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0L2, L5L1, GSL_COMPLEX_ZERO, H0L2L5L1);
    gsl_complex trH0L2L5L1 = trace(H0L2L5L1);
    gsl_matrix_complex* L4L4L5L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L4L4, L5L5, GSL_COMPLEX_ZERO, L4L4L5L5);
    gsl_complex trL4L4L5L5 = trace(L4L4L5L5);
    gsl_matrix_complex* H0L5L4L3 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0L5, L4L3, GSL_COMPLEX_ZERO, H0L5L4L3);
    gsl_complex trH0L5L4L3 = trace(H0L5L4L3);
    gsl_matrix_complex* H1L0L2L1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H1L0, L2L1, GSL_COMPLEX_ZERO, H1L0L2L1);
    gsl_complex trH1L0L2L1 = trace(H1L0L2L1);
    gsl_matrix_complex* H0L3L0L1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0L3, L0L1, GSL_COMPLEX_ZERO, H0L3L0L1);
    gsl_complex trH0L3L0L1 = trace(H0L3L0L1);
    gsl_matrix_complex* H1H1L5L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H1H1, L5L5, GSL_COMPLEX_ZERO, H1H1L5L5);
    gsl_complex trH1H1L5L5 = trace(H1H1L5L5);
    gsl_matrix_complex* L2L3L2L3 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, L2L3, L2L3, GSL_COMPLEX_ZERO, L2L3L2L3);
    gsl_complex trL2L3L2L3 = trace(L2L3L2L3);
    gsl_matrix_complex* L0L5L4L1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, L0L5, L4L1, GSL_COMPLEX_ZERO, L0L5L4L1);
    gsl_complex trL0L5L4L1 = trace(L0L5L4L1);
    gsl_matrix_complex* H0L5L1L2 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0L5, L1L2, GSL_COMPLEX_ZERO, H0L5L1L2);
    gsl_complex trH0L5L1L2 = trace(H0L5L1L2);
    gsl_matrix_complex* H0H1L1L4 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0H1, L1L4, GSL_COMPLEX_ZERO, H0H1L1L4);
    gsl_complex trH0H1L1L4 = trace(H0H1L1L4);
    gsl_matrix_complex* L2L2L4L4 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L2L2, L4L4, GSL_COMPLEX_ZERO, L2L2L4L4);
    gsl_complex trL2L2L4L4 = trace(L2L2L4L4);
    gsl_matrix_complex* H0L1L5L2 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0L1, L5L2, GSL_COMPLEX_ZERO, H0L1L5L2);
    gsl_complex trH0L1L5L2 = trace(H0L1L5L2);
    gsl_matrix_complex* L2L5L2L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, L2L5, L2L5, GSL_COMPLEX_ZERO, L2L5L2L5);
    gsl_complex trL2L5L2L5 = trace(L2L5L2L5);
    gsl_matrix_complex* L0L4L1L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, L0L4, L1L5, GSL_COMPLEX_ZERO, L0L4L1L5);
    gsl_complex trL0L4L1L5 = trace(L0L4L1L5);
    gsl_matrix_complex* L0L4L5L1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, L0L4, L5L1, GSL_COMPLEX_ZERO, L0L4L5L1);
    gsl_complex trL0L4L5L1 = trace(L0L4L5L1);
    gsl_matrix_complex* L0L0L5L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L0L0, L5L5, GSL_COMPLEX_ZERO, L0L0L5L5);
    gsl_complex trL0L0L5L5 = trace(L0L0L5L5);
    gsl_matrix_complex* L1L4L1L4 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, L1L4, L1L4, GSL_COMPLEX_ZERO, L1L4L1L4);
    gsl_complex trL1L4L1L4 = trace(L1L4L1L4);
    gsl_matrix_complex* H0H0L2L2 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H0H0, L2L2, GSL_COMPLEX_ZERO, H0H0L2L2);
    gsl_complex trH0H0L2L2 = trace(H0H0L2L2);
    gsl_matrix_complex* H1L0L4L3 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H1L0, L4L3, GSL_COMPLEX_ZERO, H1L0L4L3);
    gsl_complex trH1L0L4L3 = trace(H1L0L4L3);
    gsl_matrix_complex* H1L5L4L2 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H1L5, L4L2, GSL_COMPLEX_ZERO, H1L5L4L2);
    gsl_complex trH1L5L4L2 = trace(H1L5L4L2);
    gsl_matrix_complex* H1L4L0L3 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H1L4, L0L3, GSL_COMPLEX_ZERO, H1L4L0L3);
    gsl_complex trH1L4L0L3 = trace(H1L4L0L3);
    gsl_matrix_complex* H1L2L0L1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H1L2, L0L1, GSL_COMPLEX_ZERO, H1L2L0L1);
    gsl_complex trH1L2L0L1 = trace(H1L2L0L1);
    gsl_matrix_complex* L0L0L3L3 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L0L0, L3L3, GSL_COMPLEX_ZERO, L0L0L3L3);
    gsl_complex trL0L0L3L3 = trace(L0L0L3L3);
    gsl_matrix_complex* H1L0H1L0 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H1L0, H1L0, GSL_COMPLEX_ZERO, H1L0H1L0);
    gsl_complex trH1L0H1L0 = trace(H1L0H1L0);
    gsl_matrix_complex* H0L3L1L0 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0L3, L1L0, GSL_COMPLEX_ZERO, H0L3L1L0);
    gsl_complex trH0L3L1L0 = trace(H0L3L1L0);
    gsl_matrix_complex* H1L2L5L4 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H1L2, L5L4, GSL_COMPLEX_ZERO, H1L2L5L4);
    gsl_complex trH1L2L5L4 = trace(H1L2L5L4);
    gsl_matrix_complex* H1L2H1L2 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H1L2, H1L2, GSL_COMPLEX_ZERO, H1L2H1L2);
    gsl_complex trH1L2H1L2 = trace(H1L2H1L2);
    gsl_matrix_complex* L1L2L1L2 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, L1L2, L1L2, GSL_COMPLEX_ZERO, L1L2L1L2);
    gsl_complex trL1L2L1L2 = trace(L1L2L1L2);
    gsl_matrix_complex* H0H1L2L3 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0H1, L2L3, GSL_COMPLEX_ZERO, H0H1L2L3);
    gsl_complex trH0H1L2L3 = trace(H0H1L2L3);
    gsl_matrix_complex* L1L1L1L1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L1L1, L1L1, GSL_COMPLEX_ZERO, L1L1L1L1);
    gsl_complex trL1L1L1L1 = trace(L1L1L1L1);
    gsl_matrix_complex* H0H0L0L0 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H0H0, L0L0, GSL_COMPLEX_ZERO, H0H0L0L0);
    gsl_complex trH0H0L0L0 = trace(H0H0L0L0);
    gsl_matrix_complex* H0H1L3L2 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0H1, L3L2, GSL_COMPLEX_ZERO, H0H1L3L2);
    gsl_complex trH0H1L3L2 = trace(H0H1L3L2);
    gsl_matrix_complex* H0L5H0L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0L5, H0L5, GSL_COMPLEX_ZERO, H0L5H0L5);
    gsl_complex trH0L5H0L5 = trace(H0L5H0L5);
    gsl_matrix_complex* H0L2L4L0 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0L2, L4L0, GSL_COMPLEX_ZERO, H0L2L4L0);
    gsl_complex trH0L2L4L0 = trace(H0L2L4L0);
    gsl_matrix_complex* H0L2L0L4 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0L2, L0L4, GSL_COMPLEX_ZERO, H0L2L0L4);
    gsl_complex trH0L2L0L4 = trace(H0L2L0L4);
    gsl_matrix_complex* L1L1L5L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L1L1, L5L5, GSL_COMPLEX_ZERO, L1L1L5L5);
    gsl_complex trL1L1L5L5 = trace(L1L1L5L5);
    gsl_matrix_complex* H0L2L3H1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0L2, L3H1, GSL_COMPLEX_ZERO, H0L2L3H1);
    gsl_complex trH0L2L3H1 = trace(H0L2L3H1);
    gsl_matrix_complex* L1L2L4L3 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, L1L2, L4L3, GSL_COMPLEX_ZERO, L1L2L4L3);
    gsl_complex trL1L2L4L3 = trace(L1L2L4L3);
    gsl_matrix_complex* H1L3L1L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H1L3, L1L5, GSL_COMPLEX_ZERO, H1L3L1L5);
    gsl_complex trH1L3L1L5 = trace(H1L3L1L5);
    gsl_matrix_complex* H0H0L1L1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H0H0, L1L1, GSL_COMPLEX_ZERO, H0H0L1L1);
    gsl_complex trH0H0L1L1 = trace(H0H0L1L1);
    gsl_matrix_complex* H0L4L1H1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0L4, L1H1, GSL_COMPLEX_ZERO, H0L4L1H1);
    gsl_complex trH0L4L1H1 = trace(H0L4L1H1);
    gsl_matrix_complex* H0L1H1L4 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0L1, H1L4, GSL_COMPLEX_ZERO, H0L1H1L4);
    gsl_complex trH0L1H1L4 = trace(H0L1H1L4);
    gsl_matrix_complex* H1L4L3L0 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H1L4, L3L0, GSL_COMPLEX_ZERO, H1L4L3L0);
    gsl_complex trH1L4L3L0 = trace(H1L4L3L0);
    gsl_matrix_complex* L2L4L2L4 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, L2L4, L2L4, GSL_COMPLEX_ZERO, L2L4L2L4);
    gsl_complex trL2L4L2L4 = trace(L2L4L2L4);
    gsl_matrix_complex* L2L2L5L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L2L2, L5L5, GSL_COMPLEX_ZERO, L2L2L5L5);
    gsl_complex trL2L2L5L5 = trace(L2L2L5L5);
    gsl_matrix_complex* H0H0L3L3 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H0H0, L3L3, GSL_COMPLEX_ZERO, H0H0L3L3);
    gsl_complex trH0H0L3L3 = trace(H0H0L3L3);
    gsl_matrix_complex* H0H1L5L0 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0H1, L5L0, GSL_COMPLEX_ZERO, H0H1L5L0);
    gsl_complex trH0H1L5L0 = trace(H0H1L5L0);
    gsl_matrix_complex* L0L1L0L1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, L0L1, L0L1, GSL_COMPLEX_ZERO, L0L1L0L1);
    gsl_complex trL0L1L0L1 = trace(L0L1L0L1);
    gsl_matrix_complex* H1L4H1L4 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H1L4, H1L4, GSL_COMPLEX_ZERO, H1L4H1L4);
    gsl_complex trH1L4H1L4 = trace(H1L4H1L4);
    gsl_matrix_complex* L0L1L5L4 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, L0L1, L5L4, GSL_COMPLEX_ZERO, L0L1L5L4);
    gsl_complex trL0L1L5L4 = trace(L0L1L5L4);
    gsl_matrix_complex* H1L0L3L4 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H1L0, L3L4, GSL_COMPLEX_ZERO, H1L0L3L4);
    gsl_complex trH1L0L3L4 = trace(H1L0L3L4);
    gsl_matrix_complex* L0L1L4L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, L0L1, L4L5, GSL_COMPLEX_ZERO, L0L1L4L5);
    gsl_complex trL0L1L4L5 = trace(L0L1L4L5);
    gsl_matrix_complex* H0L5L3L4 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0L5, L3L4, GSL_COMPLEX_ZERO, H0L5L3L4);
    gsl_complex trH0L5L3L4 = trace(H0L5L3L4);
    gsl_matrix_complex* L0L5L1L4 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, L0L5, L1L4, GSL_COMPLEX_ZERO, L0L5L1L4);
    gsl_complex trL0L5L1L4 = trace(L0L5L1L4);
    gsl_matrix_complex* L0L2L3L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, L0L2, L3L5, GSL_COMPLEX_ZERO, L0L2L3L5);
    gsl_complex trL0L2L3L5 = trace(L0L2L3L5);
    gsl_matrix_complex* H0L4L0L2 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0L4, L0L2, GSL_COMPLEX_ZERO, H0L4L0L2);
    gsl_complex trH0L4L0L2 = trace(H0L4L0L2);
    gsl_matrix_complex* H0L5H1L0 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0L5, H1L0, GSL_COMPLEX_ZERO, H0L5H1L0);
    gsl_complex trH0L5H1L0 = trace(H0L5H1L0);
    gsl_matrix_complex* L2L2L2L2 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L2L2, L2L2, GSL_COMPLEX_ZERO, L2L2L2L2);
    gsl_complex trL2L2L2L2 = trace(L2L2L2L2);
    gsl_matrix_complex* H0L4L2L0 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0L4, L2L0, GSL_COMPLEX_ZERO, H0L4L2L0);
    gsl_complex trH0L4L2L0 = trace(H0L4L2L0);
    gsl_matrix_complex* H1L1L3L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H1L1, L3L5, GSL_COMPLEX_ZERO, H1L1L3L5);
    gsl_complex trH1L1L3L5 = trace(H1L1L3L5);
    gsl_matrix_complex* H1L5L1L3 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H1L5, L1L3, GSL_COMPLEX_ZERO, H1L5L1L3);
    gsl_complex trH1L5L1L3 = trace(H1L5L1L3);
    gsl_matrix_complex* L5L5L5L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L5L5, L5L5, GSL_COMPLEX_ZERO, L5L5L5L5);
    gsl_complex trL5L5L5L5 = trace(L5L5L5L5);
    gsl_matrix_complex* H1L1H1L1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H1L1, H1L1, GSL_COMPLEX_ZERO, H1L1H1L1);
    gsl_complex trH1L1H1L1 = trace(H1L1H1L1);
    gsl_matrix_complex* L1L1L4L4 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L1L1, L4L4, GSL_COMPLEX_ZERO, L1L1L4L4);
    gsl_complex trL1L1L4L4 = trace(L1L1L4L4);
    gsl_matrix_complex* H0L3L2H1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0L3, L2H1, GSL_COMPLEX_ZERO, H0L3L2H1);
    gsl_complex trH0L3L2H1 = trace(H0L3L2H1);
    gsl_matrix_complex* L0L5L2L3 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, L0L5, L2L3, GSL_COMPLEX_ZERO, L0L5L2L3);
    gsl_complex trL0L5L2L3 = trace(L0L5L2L3);
    gsl_matrix_complex* H1L5L2L4 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H1L5, L2L4, GSL_COMPLEX_ZERO, H1L5L2L4);
    gsl_complex trH1L5L2L4 = trace(H1L5L2L4);
    gsl_matrix_complex* H0L4L5L3 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0L4, L5L3, GSL_COMPLEX_ZERO, H0L4L5L3);
    gsl_complex trH0L4L5L3 = trace(H0L4L5L3);
    gsl_matrix_complex* L0L0L2L2 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L0L0, L2L2, GSL_COMPLEX_ZERO, L0L0L2L2);
    gsl_complex trL0L0L2L2 = trace(L0L0L2L2);
    gsl_matrix_complex* H0H1H0H1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0H1, H0H1, GSL_COMPLEX_ZERO, H0H1H0H1);
    gsl_complex trH0H1H0H1 = trace(H0H1H0H1);
    gsl_matrix_complex* H0L1L4H1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0L1, L4H1, GSL_COMPLEX_ZERO, H0L1L4H1);
    gsl_complex trH0L1L4H1 = trace(H0L1L4H1);
    gsl_matrix_complex* L3L3L5L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L3L3, L5L5, GSL_COMPLEX_ZERO, L3L3L5L5);
    gsl_complex trL3L3L5L5 = trace(L3L3L5L5);
    gsl_matrix_complex* H1L4L5L2 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H1L4, L5L2, GSL_COMPLEX_ZERO, H1L4L5L2);
    gsl_complex trH1L4L5L2 = trace(H1L4L5L2);
    gsl_matrix_complex* H1L2L4L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H1L2, L4L5, GSL_COMPLEX_ZERO, H1L2L4L5);
    gsl_complex trH1L2L4L5 = trace(H1L2L4L5);
    gsl_matrix_complex* L0L3L0L3 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, L0L3, L0L3, GSL_COMPLEX_ZERO, L0L3L0L3);
    gsl_complex trL0L3L0L3 = trace(L0L3L0L3);
    gsl_matrix_complex* H0L0L3L1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0L0, L3L1, GSL_COMPLEX_ZERO, H0L0L3L1);
    gsl_complex trH0L0L3L1 = trace(H0L0L3L1);
    gsl_matrix_complex* L0L0L1L1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L0L0, L1L1, GSL_COMPLEX_ZERO, L0L0L1L1);
    gsl_complex trL0L0L1L1 = trace(L0L0L1L1);
    gsl_matrix_complex* H1L3H1L3 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H1L3, H1L3, GSL_COMPLEX_ZERO, H1L3H1L3);
    gsl_complex trH1L3H1L3 = trace(H1L3H1L3);
    gsl_matrix_complex* H1L3L4L0 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H1L3, L4L0, GSL_COMPLEX_ZERO, H1L3L4L0);
    gsl_complex trH1L3L4L0 = trace(H1L3L4L0);
    gsl_matrix_complex* H0L0L5H1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0L0, L5H1, GSL_COMPLEX_ZERO, H0L0L5H1);
    gsl_complex trH0L0L5H1 = trace(H0L0L5H1);
    gsl_matrix_complex* H0L5L0H1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0L5, L0H1, GSL_COMPLEX_ZERO, H0L5L0H1);
    gsl_complex trH0L5L0H1 = trace(H0L5L0H1);
    gsl_matrix_complex* L3L3L4L4 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L3L3, L4L4, GSL_COMPLEX_ZERO, L3L3L4L4);
    gsl_complex trL3L3L4L4 = trace(L3L3L4L4);
    gsl_matrix_complex* L4L4L4L4 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L4L4, L4L4, GSL_COMPLEX_ZERO, L4L4L4L4);
    gsl_complex trL4L4L4L4 = trace(L4L4L4L4);
    gsl_matrix_complex* H1H1L3L3 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H1H1, L3L3, GSL_COMPLEX_ZERO, H1H1L3L3);
    gsl_complex trH1H1L3L3 = trace(H1H1L3L3);
    gsl_matrix_complex* H0L4H1L1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0L4, H1L1, GSL_COMPLEX_ZERO, H0L4H1L1);
    gsl_complex trH0L4H1L1 = trace(H0L4H1L1);
    gsl_matrix_complex* L1L3L4L2 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, L1L3, L4L2, GSL_COMPLEX_ZERO, L1L3L4L2);
    gsl_complex trL1L3L4L2 = trace(L1L3L4L2);
    gsl_matrix_complex* H1L2L1L0 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H1L2, L1L0, GSL_COMPLEX_ZERO, H1L2L1L0);
    gsl_complex trH1L2L1L0 = trace(H1L2L1L0);
    gsl_matrix_complex* H0L4L3L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0L4, L3L5, GSL_COMPLEX_ZERO, H0L4L3L5);
    gsl_complex trH0L4L3L5 = trace(H0L4L3L5);
    gsl_matrix_complex* H0L1L3L0 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0L1, L3L0, GSL_COMPLEX_ZERO, H0L1L3L0);
    gsl_complex trH0L1L3L0 = trace(H0L1L3L0);
    gsl_matrix_complex* H0L0L1L3 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0L0, L1L3, GSL_COMPLEX_ZERO, H0L0L1L3);
    gsl_complex trH0L0L1L3 = trace(H0L0L1L3);
    gsl_matrix_complex* L0L4L0L4 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, L0L4, L0L4, GSL_COMPLEX_ZERO, L0L4L0L4);
    gsl_complex trL0L4L0L4 = trace(L0L4L0L4);
    gsl_matrix_complex* H0H1L4L1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0H1, L4L1, GSL_COMPLEX_ZERO, H0H1L4L1);
    gsl_complex trH0H1L4L1 = trace(H0H1L4L1);
    gsl_matrix_complex* H0L2H0L2 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0L2, H0L2, GSL_COMPLEX_ZERO, H0L2H0L2);
    gsl_complex trH0L2H0L2 = trace(H0L2H0L2);
    gsl_matrix_complex* H0L0H1L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0L0, H1L5, GSL_COMPLEX_ZERO, H0L0H1L5);
    gsl_complex trH0L0H1L5 = trace(H0L0H1L5);
    gsl_matrix_complex* H0L0L4L2 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0L0, L4L2, GSL_COMPLEX_ZERO, H0L0L4L2);
    gsl_complex trH0L0L4L2 = trace(H0L0L4L2);
    gsl_matrix_complex* H0L4H0L4 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0L4, H0L4, GSL_COMPLEX_ZERO, H0L4H0L4);
    gsl_complex trH0L4H0L4 = trace(H0L4H0L4);
    gsl_matrix_complex* L1L1L3L3 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L1L1, L3L3, GSL_COMPLEX_ZERO, L1L1L3L3);
    gsl_complex trL1L1L3L3 = trace(L1L1L3L3);
    gsl_matrix_complex* H1L1L2L0 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H1L1, L2L0, GSL_COMPLEX_ZERO, H1L1L2L0);
    gsl_complex trH1L1L2L0 = trace(H1L1L2L0);
    gsl_matrix_complex* H1L1L5L3 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H1L1, L5L3, GSL_COMPLEX_ZERO, H1L1L5L3);
    gsl_complex trH1L1L5L3 = trace(H1L1L5L3);
    gsl_matrix_complex* L0L2L0L2 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, L0L2, L0L2, GSL_COMPLEX_ZERO, L0L2L0L2);
    gsl_complex trL0L2L0L2 = trace(L0L2L0L2);
    gsl_matrix_complex* H0L3H0L3 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0L3, H0L3, GSL_COMPLEX_ZERO, H0L3H0L3);
    gsl_complex trH0L3H0L3 = trace(H0L3H0L3);
    gsl_matrix_complex* L3L5L3L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, L3L5, L3L5, GSL_COMPLEX_ZERO, L3L5L3L5);
    gsl_complex trL3L5L3L5 = trace(L3L5L3L5);
    gsl_matrix_complex* L4L5L4L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, L4L5, L4L5, GSL_COMPLEX_ZERO, L4L5L4L5);
    gsl_complex trL4L5L4L5 = trace(L4L5L4L5);
    gsl_matrix_complex* L0L0L0L0 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L0L0, L0L0, GSL_COMPLEX_ZERO, L0L0L0L0);
    gsl_complex trL0L0L0L0 = trace(L0L0L0L0);
    gsl_matrix_complex* H0L3L5L4 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0L3, L5L4, GSL_COMPLEX_ZERO, H0L3L5L4);
    gsl_complex trH0L3L5L4 = trace(H0L3L5L4);
    gsl_matrix_complex* H1L5H1L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H1L5, H1L5, GSL_COMPLEX_ZERO, H1L5H1L5);
    gsl_complex trH1L5H1L5 = trace(H1L5H1L5);
    gsl_matrix_complex* H0H0H0H0 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H0H0, H0H0, GSL_COMPLEX_ZERO, H0H0H0H0);
    gsl_complex trH0H0H0H0 = trace(H0H0H0H0);
    gsl_matrix_complex* H1L5L3L1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H1L5, L3L1, GSL_COMPLEX_ZERO, H1L5L3L1);
    gsl_complex trH1L5L3L1 = trace(H1L5L3L1);
    gsl_matrix_complex* H0L3H1L2 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0L3, H1L2, GSL_COMPLEX_ZERO, H0L3H1L2);
    gsl_complex trH0L3H1L2 = trace(H0L3H1L2);
    gsl_matrix_complex* L0L0L4L4 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L0L0, L4L4, GSL_COMPLEX_ZERO, L0L0L4L4);
    gsl_complex trL0L0L4L4 = trace(L0L0L4L4);
    gsl_matrix_complex* H1H1L4L4 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H1H1, L4L4, GSL_COMPLEX_ZERO, H1H1L4L4);
    gsl_complex trH1H1L4L4 = trace(H1H1L4L4);
    gsl_matrix_complex* L3L3L3L3 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, L3L3, L3L3, GSL_COMPLEX_ZERO, L3L3L3L3);
    gsl_complex trL3L3L3L3 = trace(L3L3L3L3);
    gsl_matrix_complex* H0H1L0L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0H1, L0L5, GSL_COMPLEX_ZERO, H0H1L0L5);
    gsl_complex trH0H1L0L5 = trace(H0H1L0L5);
    gsl_matrix_complex* H0L1L2L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0L1, L2L5, GSL_COMPLEX_ZERO, H0L1L2L5);
    gsl_complex trH0L1L2L5 = trace(H0L1L2L5);
    gsl_matrix_complex* L1L5L1L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, L1L5, L1L5, GSL_COMPLEX_ZERO, L1L5L1L5);
    gsl_complex trL1L5L1L5 = trace(L1L5L1L5);
    gsl_matrix_complex* H0L2H1L3 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0L2, H1L3, GSL_COMPLEX_ZERO, H0L2H1L3);
    gsl_complex trH0L2H1L3 = trace(H0L2H1L3);
    gsl_matrix_complex* H1H1H1H1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H1H1, H1H1, GSL_COMPLEX_ZERO, H1H1H1H1);
    gsl_complex trH1H1H1H1 = trace(H1H1H1H1);
    gsl_matrix_complex* H0L3L4L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0L3, L4L5, GSL_COMPLEX_ZERO, H0L3L4L5);
    gsl_complex trH0L3L4L5 = trace(H0L3L4L5);
    gsl_matrix_complex* H1L3L5L1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H1L3, L5L1, GSL_COMPLEX_ZERO, H1L3L5L1);
    gsl_complex trH1L3L5L1 = trace(H1L3L5L1);
    gsl_matrix_complex* H0H0L4L4 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H0H0, L4L4, GSL_COMPLEX_ZERO, H0H0L4L4);
    gsl_complex trH0H0L4L4 = trace(H0H0L4L4);
    gsl_matrix_complex* L1L4L2L3 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, L1L4, L2L3, GSL_COMPLEX_ZERO, L1L4L2L3);
    gsl_complex trL1L4L2L3 = trace(L1L4L2L3);
    gsl_matrix_complex* H1L3L0L4 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H1L3, L0L4, GSL_COMPLEX_ZERO, H1L3L0L4);
    gsl_complex trH1L3L0L4 = trace(H1L3L0L4);
    gsl_matrix_complex* L0L5L0L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, L0L5, L0L5, GSL_COMPLEX_ZERO, L0L5L0L5);
    gsl_complex trL0L5L0L5 = trace(L0L5L0L5);
    gsl_matrix_complex* H0L2L1L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0L2, L1L5, GSL_COMPLEX_ZERO, H0L2L1L5);
    gsl_complex trH0L2L1L5 = trace(H0L2L1L5);
    gsl_matrix_complex* H0H0L5L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H0H0, L5L5, GSL_COMPLEX_ZERO, H0H0L5L5);
    gsl_complex trH0H0L5L5 = trace(H0H0L5L5);
    gsl_matrix_complex* L0L2L5L3 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, L0L2, L5L3, GSL_COMPLEX_ZERO, L0L2L5L3);
    gsl_complex trL0L2L5L3 = trace(L0L2L5L3);
    gsl_matrix_complex* H0H0H1H1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zhemm(CblasLeft, CblasUpper, GSL_COMPLEX_ONE, H0H0, H1H1, GSL_COMPLEX_ZERO, H0H0H1H1);
    gsl_complex trH0H0H1H1 = trace(H0H0H1H1);
    gsl_matrix_complex* L0L3L2L5 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, L0L3, L2L5, GSL_COMPLEX_ZERO, L0L3L2L5);
    gsl_complex trL0L3L2L5 = trace(L0L3L2L5);
    gsl_matrix_complex* H1L0L1L2 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H1L0, L1L2, GSL_COMPLEX_ZERO, H1L0L1L2);
    gsl_complex trH1L0L1L2 = trace(H1L0L1L2);
    gsl_matrix_complex* H0L1H0L1 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0L1, H0L1, GSL_COMPLEX_ZERO, H0L1H0L1);
    gsl_complex trH0L1H0L1 = trace(H0L1H0L1);
    gsl_matrix_complex* H0L0L2L4 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0L0, L2L4, GSL_COMPLEX_ZERO, H0L0L2L4);
    gsl_complex trH0L0L2L4 = trace(H0L0L2L4);
    gsl_matrix_complex* L0L5L3L2 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, L0L5, L3L2, GSL_COMPLEX_ZERO, L0L5L3L2);
    gsl_complex trL0L5L3L2 = trace(L0L5L3L2);
    gsl_matrix_complex* L1L4L3L2 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, L1L4, L3L2, GSL_COMPLEX_ZERO, L1L4L3L2);
    gsl_complex trL1L4L3L2 = trace(L1L4L3L2);
    gsl_matrix_complex* L1L2L3L4 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, L1L2, L3L4, GSL_COMPLEX_ZERO, L1L2L3L4);
    gsl_complex trL1L2L3L4 = trace(L1L2L3L4);
    gsl_matrix_complex* H0L0H0L0 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, H0L0, H0L0, GSL_COMPLEX_ZERO, H0L0H0L0);
    gsl_complex trH0L0H0L0 = trace(H0L0H0L0);
    gsl_matrix_complex* L1L3L2L4 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, L1L3, L2L4, GSL_COMPLEX_ZERO, L1L3L2L4);
    gsl_complex trL1L3L2L4 = trace(L1L3L2L4);
    gsl_matrix_complex* L1L3L1L3 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, L1L3, L1L3, GSL_COMPLEX_ZERO, L1L3L1L3);
    gsl_complex trL1L3L1L3 = trace(L1L3L1L3);
    gsl_matrix_complex* L3L4L3L4 = gsl_matrix_complex_calloc(dim, dim);
    gsl_blas_zgemm(CblasNoTrans, CblasNoTrans, GSL_COMPLEX_ONE, L3L4, L3L4, GSL_COMPLEX_ZERO, L3L4L3L4);
    gsl_complex trL3L4L3L4 = trace(L3L4L3L4);
    gsl_matrix_complex_free(L3L5);
    gsl_matrix_complex_free(H0L1);
    gsl_matrix_complex_free(H0H0);
    gsl_matrix_complex_free(L1L4);
    gsl_matrix_complex_free(L1L2);
    gsl_matrix_complex_free(H1L0);
    gsl_matrix_complex_free(H1L3);
    gsl_matrix_complex_free(L2L4);
    gsl_matrix_complex_free(L3L4);
    gsl_matrix_complex_free(L1L3);
    gsl_matrix_complex_free(L0L1);
    gsl_matrix_complex_free(L1L1);
    gsl_matrix_complex_free(L0L3);
    gsl_matrix_complex_free(L2L5);
    gsl_matrix_complex_free(L4L5);
    gsl_matrix_complex_free(L2L3);
    gsl_matrix_complex_free(L0L4);
    gsl_matrix_complex_free(H0L3);
    gsl_matrix_complex_free(H1L5);
    gsl_matrix_complex_free(H0L5);
    gsl_matrix_complex_free(L0L2);
    gsl_matrix_complex_free(L4L4);
    gsl_matrix_complex_free(L3L3);
    gsl_matrix_complex_free(L0L5);
    gsl_matrix_complex_free(L5L5);
    gsl_matrix_complex_free(H0L4);
    gsl_matrix_complex_free(H1L4);
    gsl_matrix_complex_free(L0L0);
    gsl_matrix_complex_free(L2L2);
    gsl_matrix_complex_free(H1L2);
    gsl_matrix_complex_free(H0H1);
    gsl_matrix_complex_free(H0L2);
    gsl_matrix_complex_free(H1L1);
    gsl_matrix_complex_free(H1H1);
    gsl_matrix_complex_free(H0L0);
    gsl_matrix_complex_free(L1L5);
    gsl_matrix_complex_free(L5L4);
    gsl_matrix_complex_free(L4H1);
    gsl_matrix_complex_free(L4L1);
    gsl_matrix_complex_free(L5L1);
    gsl_matrix_complex_free(L5H1);
    gsl_matrix_complex_free(L0H1);
    gsl_matrix_complex_free(L5L3);
    gsl_matrix_complex_free(L2H1);
    gsl_matrix_complex_free(L3H1);
    gsl_matrix_complex_free(L4L2);
    gsl_matrix_complex_free(L3L2);
    gsl_matrix_complex_free(L2L1);
    gsl_matrix_complex_free(L2L0);
    gsl_matrix_complex_free(L4L0);
    gsl_matrix_complex_free(L3L1);
    gsl_matrix_complex_free(L1L0);
    gsl_matrix_complex_free(L5L2);
    gsl_matrix_complex_free(L5L0);
    gsl_matrix_complex_free(L1H1);
    gsl_matrix_complex_free(L3L0);
    gsl_matrix_complex_free(L4L3);
    gsl_matrix_complex_free(L0L2L4);
    gsl_matrix_complex_free(L3L5L4);
    gsl_matrix_complex_free(L2L4L5);
    gsl_matrix_complex_free(H0L1L4);
    gsl_matrix_complex_free(L1L5L2);
    gsl_matrix_complex_free(H1L1L4);
    gsl_matrix_complex_free(H0L5L0);
    gsl_matrix_complex_free(H0L4L1);
    gsl_matrix_complex_free(H1L0L0);
    gsl_matrix_complex_free(L3L4L5);
    gsl_matrix_complex_free(H0L0L0);
    gsl_matrix_complex_free(H0L2L2);
    gsl_matrix_complex_free(L0L2L1);
    gsl_matrix_complex_free(H0L2L3);
    gsl_matrix_complex_free(L1L5L3);
    gsl_matrix_complex_free(L0L3L1);
    gsl_matrix_complex_free(L1L2L5);
    gsl_matrix_complex_free(L0L1L2);
    gsl_matrix_complex_free(H1L2L3);
    gsl_matrix_complex_free(H1L2L2);
    gsl_matrix_complex_free(H1H1H1);
    gsl_matrix_complex_free(H0L4L4);
    gsl_matrix_complex_free(H1L3L3);
    gsl_matrix_complex_free(H0L1L1);
    gsl_matrix_complex_free(L1L3L5);
    gsl_matrix_complex_free(H1L3L2);
    gsl_matrix_complex_free(H1L5L0);
    gsl_matrix_complex_free(H0H0H0);
    gsl_matrix_complex_free(H0L3L3);
    gsl_matrix_complex_free(H0H1H1);
    gsl_matrix_complex_free(H1L4L1);
    gsl_matrix_complex_free(H0L0L5);
    gsl_matrix_complex_free(H1L5L5);
    gsl_matrix_complex_free(L2L5L4);
    gsl_matrix_complex_free(H0H0H1);
    gsl_matrix_complex_free(L0L4L3);
    gsl_matrix_complex_free(H0L3L2);
    gsl_matrix_complex_free(L0L4L2);
    gsl_matrix_complex_free(H0L5L5);
    gsl_matrix_complex_free(H1L0L5);
    gsl_matrix_complex_free(L0L1L3);
    gsl_matrix_complex_free(H1L1L1);
    gsl_matrix_complex_free(H1L4L4);
    gsl_matrix_complex_free(L0L3L4);
    gsl_matrix_complex_free(H1L4L2L5);
    gsl_matrix_complex_free(H1H1L0L0);
    gsl_matrix_complex_free(L2L2L3L3);
    gsl_matrix_complex_free(H0L1L0L3);
    gsl_matrix_complex_free(L1L1L2L2);
    gsl_matrix_complex_free(H1H1L1L1);
    gsl_matrix_complex_free(H1L1L0L2);
    gsl_matrix_complex_free(H1H1L2L2);
    gsl_matrix_complex_free(H0L5L2L1);
    gsl_matrix_complex_free(L0L3L5L2);
    gsl_matrix_complex_free(H0L2L5L1);
    gsl_matrix_complex_free(L4L4L5L5);
    gsl_matrix_complex_free(H0L5L4L3);
    gsl_matrix_complex_free(H1L0L2L1);
    gsl_matrix_complex_free(H0L3L0L1);
    gsl_matrix_complex_free(H1H1L5L5);
    gsl_matrix_complex_free(L2L3L2L3);
    gsl_matrix_complex_free(L0L5L4L1);
    gsl_matrix_complex_free(H0L5L1L2);
    gsl_matrix_complex_free(H0H1L1L4);
    gsl_matrix_complex_free(L2L2L4L4);
    gsl_matrix_complex_free(H0L1L5L2);
    gsl_matrix_complex_free(L2L5L2L5);
    gsl_matrix_complex_free(L0L4L1L5);
    gsl_matrix_complex_free(L0L4L5L1);
    gsl_matrix_complex_free(L0L0L5L5);
    gsl_matrix_complex_free(L1L4L1L4);
    gsl_matrix_complex_free(H0H0L2L2);
    gsl_matrix_complex_free(H1L0L4L3);
    gsl_matrix_complex_free(H1L5L4L2);
    gsl_matrix_complex_free(H1L4L0L3);
    gsl_matrix_complex_free(H1L2L0L1);
    gsl_matrix_complex_free(L0L0L3L3);
    gsl_matrix_complex_free(H1L0H1L0);
    gsl_matrix_complex_free(H0L3L1L0);
    gsl_matrix_complex_free(H1L2L5L4);
    gsl_matrix_complex_free(H1L2H1L2);
    gsl_matrix_complex_free(L1L2L1L2);
    gsl_matrix_complex_free(H0H1L2L3);
    gsl_matrix_complex_free(L1L1L1L1);
    gsl_matrix_complex_free(H0H0L0L0);
    gsl_matrix_complex_free(H0H1L3L2);
    gsl_matrix_complex_free(H0L5H0L5);
    gsl_matrix_complex_free(H0L2L4L0);
    gsl_matrix_complex_free(H0L2L0L4);
    gsl_matrix_complex_free(L1L1L5L5);
    gsl_matrix_complex_free(H0L2L3H1);
    gsl_matrix_complex_free(L1L2L4L3);
    gsl_matrix_complex_free(H1L3L1L5);
    gsl_matrix_complex_free(H0H0L1L1);
    gsl_matrix_complex_free(H0L4L1H1);
    gsl_matrix_complex_free(H0L1H1L4);
    gsl_matrix_complex_free(H1L4L3L0);
    gsl_matrix_complex_free(L2L4L2L4);
    gsl_matrix_complex_free(L2L2L5L5);
    gsl_matrix_complex_free(H0H0L3L3);
    gsl_matrix_complex_free(H0H1L5L0);
    gsl_matrix_complex_free(L0L1L0L1);
    gsl_matrix_complex_free(H1L4H1L4);
    gsl_matrix_complex_free(L0L1L5L4);
    gsl_matrix_complex_free(H1L0L3L4);
    gsl_matrix_complex_free(L0L1L4L5);
    gsl_matrix_complex_free(H0L5L3L4);
    gsl_matrix_complex_free(L0L5L1L4);
    gsl_matrix_complex_free(L0L2L3L5);
    gsl_matrix_complex_free(H0L4L0L2);
    gsl_matrix_complex_free(H0L5H1L0);
    gsl_matrix_complex_free(L2L2L2L2);
    gsl_matrix_complex_free(H0L4L2L0);
    gsl_matrix_complex_free(H1L1L3L5);
    gsl_matrix_complex_free(H1L5L1L3);
    gsl_matrix_complex_free(L5L5L5L5);
    gsl_matrix_complex_free(H1L1H1L1);
    gsl_matrix_complex_free(L1L1L4L4);
    gsl_matrix_complex_free(H0L3L2H1);
    gsl_matrix_complex_free(L0L5L2L3);
    gsl_matrix_complex_free(H1L5L2L4);
    gsl_matrix_complex_free(H0L4L5L3);
    gsl_matrix_complex_free(L0L0L2L2);
    gsl_matrix_complex_free(H0H1H0H1);
    gsl_matrix_complex_free(H0L1L4H1);
    gsl_matrix_complex_free(L3L3L5L5);
    gsl_matrix_complex_free(H1L4L5L2);
    gsl_matrix_complex_free(H1L2L4L5);
    gsl_matrix_complex_free(L0L3L0L3);
    gsl_matrix_complex_free(H0L0L3L1);
    gsl_matrix_complex_free(L0L0L1L1);
    gsl_matrix_complex_free(H1L3H1L3);
    gsl_matrix_complex_free(H1L3L4L0);
    gsl_matrix_complex_free(H0L0L5H1);
    gsl_matrix_complex_free(H0L5L0H1);
    gsl_matrix_complex_free(L3L3L4L4);
    gsl_matrix_complex_free(L4L4L4L4);
    gsl_matrix_complex_free(H1H1L3L3);
    gsl_matrix_complex_free(H0L4H1L1);
    gsl_matrix_complex_free(L1L3L4L2);
    gsl_matrix_complex_free(H1L2L1L0);
    gsl_matrix_complex_free(H0L4L3L5);
    gsl_matrix_complex_free(H0L1L3L0);
    gsl_matrix_complex_free(H0L0L1L3);
    gsl_matrix_complex_free(L0L4L0L4);
    gsl_matrix_complex_free(H0H1L4L1);
    gsl_matrix_complex_free(H0L2H0L2);
    gsl_matrix_complex_free(H0L0H1L5);
    gsl_matrix_complex_free(H0L0L4L2);
    gsl_matrix_complex_free(H0L4H0L4);
    gsl_matrix_complex_free(L1L1L3L3);
    gsl_matrix_complex_free(H1L1L2L0);
    gsl_matrix_complex_free(H1L1L5L3);
    gsl_matrix_complex_free(L0L2L0L2);
    gsl_matrix_complex_free(H0L3H0L3);
    gsl_matrix_complex_free(L3L5L3L5);
    gsl_matrix_complex_free(L4L5L4L5);
    gsl_matrix_complex_free(L0L0L0L0);
    gsl_matrix_complex_free(H0L3L5L4);
    gsl_matrix_complex_free(H1L5H1L5);
    gsl_matrix_complex_free(H0H0H0H0);
    gsl_matrix_complex_free(H1L5L3L1);
    gsl_matrix_complex_free(H0L3H1L2);
    gsl_matrix_complex_free(L0L0L4L4);
    gsl_matrix_complex_free(H1H1L4L4);
    gsl_matrix_complex_free(L3L3L3L3);
    gsl_matrix_complex_free(H0H1L0L5);
    gsl_matrix_complex_free(H0L1L2L5);
    gsl_matrix_complex_free(L1L5L1L5);
    gsl_matrix_complex_free(H0L2H1L3);
    gsl_matrix_complex_free(H1H1H1H1);
    gsl_matrix_complex_free(H0L3L4L5);
    gsl_matrix_complex_free(H1L3L5L1);
    gsl_matrix_complex_free(H0H0L4L4);
    gsl_matrix_complex_free(L1L4L2L3);
    gsl_matrix_complex_free(H1L3L0L4);
    gsl_matrix_complex_free(L0L5L0L5);
    gsl_matrix_complex_free(H0L2L1L5);
    gsl_matrix_complex_free(H0H0L5L5);
    gsl_matrix_complex_free(L0L2L5L3);
    gsl_matrix_complex_free(H0H0H1H1);
    gsl_matrix_complex_free(L0L3L2L5);
    gsl_matrix_complex_free(H1L0L1L2);
    gsl_matrix_complex_free(H0L1H0L1);
    gsl_matrix_complex_free(H0L0L2L4);
    gsl_matrix_complex_free(L0L5L3L2);
    gsl_matrix_complex_free(L1L4L3L2);
    gsl_matrix_complex_free(L1L2L3L4);
    gsl_matrix_complex_free(H0L0H0L0);
    gsl_matrix_complex_free(L1L3L2L4);
    gsl_matrix_complex_free(L1L3L1L3);
    gsl_matrix_complex_free(L3L4L3L4);
    if(control[0])
        vecS[0] = G*(+8*dim*GSL_REAL(trH1H1)+8*dim*GSL_REAL(trL1L1)+8*GSL_REAL(gsl_complex_mul(trH0,trH0))+8*dim*GSL_REAL(trL2L2)+8*dim*GSL_REAL(trL5L5)+8*GSL_REAL(gsl_complex_mul(trH1,trH1))+8*dim*GSL_REAL(trL0L0)+8*dim*GSL_REAL(trL4L4)+8*dim*GSL_REAL(trL3L3)+8*dim*GSL_REAL(trH0H0)) +96*GSL_REAL(gsl_complex_mul(trH0,trH0L3L3))+32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L4L0L2))+32*GSL_REAL(gsl_complex_mul(trL3L5,trL3L5))-16*dim*GSL_REAL(trH0H1H0H1)+16*GSL_REAL(gsl_complex_mul(trH1H1,trL3L3))+32*GSL_REAL(gsl_complex_mul(trH0,trH1L1L4))+32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L0L3L1))+32*GSL_REAL(gsl_complex_mul(trH0L4L1,trH1))-64*GSL_REAL(gsl_complex_mul(trL0L5,trL2L3))-32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L3L0L4))+16*GSL_REAL(gsl_complex_mul(trL3L3,trL4L4))+96*GSL_REAL(gsl_complex_mul(trH0,trH0L4L4))+8*dim*GSL_REAL(trL5L5L5L5)-32*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.),gsl_complex_mul(trH0,trL0L3L1)))-32*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.),gsl_complex_mul(trH0,trL0L4L2)))+48*GSL_REAL(gsl_complex_mul(trH0H0,trL3L3))+32*dim*GSL_REAL(trH0L2L3H1)+16*GSL_REAL(gsl_complex_mul(trH1H1,trL5L5))+16*GSL_REAL(gsl_complex_mul(trL4L4,trL5L5))-32*dim*GSL_REAL(trH0L3H1L2)+32*GSL_REAL(gsl_complex_mul(trL0L2,trL0L2))+64*GSL_REAL(gsl_complex_mul(trL0L4,trL1L5))-32*dim*GSL_REAL(trL1L2L3L4)+16*GSL_REAL(gsl_complex_mul(trH0H0,trL1L1))+96*GSL_REAL(gsl_complex_mul(trL0L4,trL0L4))-32*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.),gsl_complex_mul(trH1,trL1L3L5)))+32*dim*GSL_REAL(trL2L2L4L4)-32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L4L5L2))+32*dim*GSL_REAL(trH1H1L4L4)+16*GSL_REAL(gsl_complex_mul(trL0L0,trL1L1))+32*dim*GSL_REAL(trH1H1L2L2)+48*GSL_REAL(gsl_complex_mul(trH0H0,trL4L4))+32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L0L2L1))+16*GSL_REAL(gsl_complex_mul(trH1H1,trL4L4))-16*dim*GSL_REAL(trL4L5L4L5)+24*GSL_REAL(gsl_complex_mul(trL0L0,trL0L0))+32*dim*GSL_REAL(trH0H0L3L3)+32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L5L3L4))+32*dim*GSL_REAL(trL0L4L5L1)-96*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.),gsl_complex_mul(trH0,trL3L5L4)))+8*dim*GSL_REAL(trL4L4L4L4)+16*GSL_REAL(gsl_complex_mul(trH0H0,trL2L2))-32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L0L3L4))+64*GSL_REAL(gsl_complex_mul(trL1L4,trL2L3))-64*GSL_REAL(gsl_complex_mul(trL0L2,trL3L5))+32*dim*GSL_REAL(trH0L4L1H1)+32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L4L3L0))+24*GSL_REAL(gsl_complex_mul(trL2L2,trL2L2))+32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L2L5L4))-16*dim*GSL_REAL(trH0L2H0L2)+32*dim*GSL_REAL(trH0L0L5H1)-32*dim*GSL_REAL(trL0L2L5L3)-32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L1L3L5))-32*GSL_REAL(gsl_complex_mul(trH0,trH1L3L2))-32*dim*GSL_REAL(trH0H1L0L5)+32*dim*GSL_REAL(trL4L4L5L5)-32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L4L2L0))-32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L1L2L0))+32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L1L5L3))+64*GSL_REAL(gsl_complex_mul(trH0L0,trH1L5))+32*GSL_REAL(gsl_complex_mul(trH1,trH1L5L5))-32*GSL_REAL(gsl_complex_mul(trH0L3L2,trH1))-32*GSL_REAL(gsl_complex_mul(trH0L5L0,trH1))+32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L5L4L2))-32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L3L1L5))-32*GSL_REAL(gsl_complex_mul(trH1L3,trH1L3))+24*GSL_REAL(gsl_complex_mul(trH1H1,trH1H1))-32*dim*GSL_REAL(trL1L4L3L2)+48*GSL_REAL(gsl_complex_mul(trL2L2,trL4L4))-32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L4L2L5))+32*GSL_REAL(gsl_complex_mul(trH1,trH1L3L3))+96*GSL_REAL(gsl_complex_mul(trL0L3,trL0L3))-64*GSL_REAL(gsl_complex_mul(trH0L4,trH1L1))+32*dim*GSL_REAL(trH1H1L0L0)+48*GSL_REAL(gsl_complex_mul(trH1H1,trL1L1))+48*GSL_REAL(gsl_complex_mul(trL0L0,trL4L4))+16*dim*GSL_REAL(trH1L2H1L2)-32*GSL_REAL(gsl_complex_mul(trH1L4,trH1L4))+24*GSL_REAL(gsl_complex_mul(trL5L5,trL5L5))-16*dim*GSL_REAL(trL0L1L0L1)+64*GSL_REAL(gsl_complex_mul(trH0L3,trH1L2))-32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L5L4L3))+32*dim*GSL_REAL(trL0L2L3L5)-32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L2L4L0))+32*dim*GSL_REAL(trH0H1L3L2)+24*GSL_REAL(gsl_complex_mul(trL4L4,trL4L4))+48*GSL_REAL(gsl_complex_mul(trL2L2,trL5L5))-32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L0L1L2))+32*dim*GSL_REAL(trL2L2L3L3)-32*GSL_REAL(gsl_complex_mul(trH0,trH1L2L3))+32*dim*GSL_REAL(trL0L5L1L4)+8*dim*GSL_REAL(trH0H0H0H0)+16*dim*GSL_REAL(trL2L4L2L4)+96*GSL_REAL(gsl_complex_mul(trH1,trH1L0L0))+32*dim*GSL_REAL(trH0H0L2L2)+24*GSL_REAL(gsl_complex_mul(trH0H0,trH0H0))+96*GSL_REAL(gsl_complex_mul(trL1L5,trL1L5))+16*dim*GSL_REAL(trH1L1H1L1)+8*dim*GSL_REAL(trL3L3L3L3)+32*GSL_REAL(gsl_complex_mul(trL0L5,trL0L5))+32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L3L0L1))-64*GSL_REAL(gsl_complex_mul(trH0L1,trH1L4))+32*dim*GSL_REAL(trL0L0L1L1)+32*dim*GSL_REAL(trL0L0L5L5)+32*dim*GSL_REAL(trL3L3L5L5)-32*GSL_REAL(gsl_complex_mul(trH1L5,trH1L5))+48*GSL_REAL(gsl_complex_mul(trH1H1,trL0L0))+96*GSL_REAL(gsl_complex_mul(trL1L3,trL1L3))-32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L1L3L0))-32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L1L0L3))-32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L2L0L1))-16*dim*GSL_REAL(trL0L5L0L5)-32*GSL_REAL(gsl_complex_mul(trH0,trH1L0L5))+32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L1L5L2))+32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L5L1L3))+32*GSL_REAL(gsl_complex_mul(trH0,trH0H0H0))-32*dim*GSL_REAL(trH0L1L4H1)+32*GSL_REAL(gsl_complex_mul(trL2L3,trL2L3))-64*GSL_REAL(gsl_complex_mul(trH0H1,trL0L5))-32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L2L1L5))+32*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.),gsl_complex_mul(trH0,trL1L2L5)))-16*dim*GSL_REAL(trL1L4L1L4)+32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L1L2L5))+16*dim*GSL_REAL(trL1L5L1L5)-96*GSL_REAL(gsl_complex_mul(trH1L2,trH1L2))+32*dim*GSL_REAL(trH0H1L1L4)-16*dim*GSL_REAL(trH1L5H1L5)+32*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.),gsl_complex_mul(trH1,trL1L5L3)))+96*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.),gsl_complex_mul(trH0,trL3L4L5)))+32*dim*GSL_REAL(trH1H1L1L1)+64*GSL_REAL(gsl_complex_mul(trL1L2,trL3L4))+8*dim*GSL_REAL(trL2L2L2L2)+32*dim*GSL_REAL(trH0H0L4L4)+16*GSL_REAL(gsl_complex_mul(trL3L3,trL5L5))+96*GSL_REAL(gsl_complex_mul(trL2L5,trL2L5))+32*dim*GSL_REAL(trH0H0H1H1)+32*dim*GSL_REAL(trL2L2L5L5)+32*dim*GSL_REAL(trH0H0L1L1)+16*dim*GSL_REAL(trL2L5L2L5)-16*dim*GSL_REAL(trH1L3H1L3)+32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L1L0L2))+32*GSL_REAL(gsl_complex_mul(trH0L1L4,trH1))+16*GSL_REAL(gsl_complex_mul(trL1L1,trL2L2))-32*dim*GSL_REAL(trH0L0H1L5)-32*dim*GSL_REAL(trL0L3L2L5)+32*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.),gsl_complex_mul(trH0,trL0L2L4)))+32*dim*GSL_REAL(trL1L3L4L2)+32*GSL_REAL(gsl_complex_mul(trH0,trH0L2L2))+32*dim*GSL_REAL(trH0L4H1L1)+16*GSL_REAL(gsl_complex_mul(trL0L0,trL2L2))-96*GSL_REAL(gsl_complex_mul(trH0L4,trH0L4))-96*GSL_REAL(gsl_complex_mul(trH0L5,trH0L5))-32*dim*GSL_REAL(trL0L3L5L2)-32*dim*GSL_REAL(trL0L5L2L3)-32*dim*GSL_REAL(trH0L2H1L3)+32*dim*GSL_REAL(trL0L5L3L2)+32*GSL_REAL(gsl_complex_mul(trL1L4,trL1L4))-16*dim*GSL_REAL(trL1L2L1L2)+32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L5L2L4))+16*dim*GSL_REAL(trH0L4H0L4)+32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L0L1L3))-32*dim*GSL_REAL(trH0H1L2L3)+32*dim*GSL_REAL(trL0L0L4L4)-16*dim*GSL_REAL(trL3L5L3L5)+48*GSL_REAL(gsl_complex_mul(trL0L0,trL3L3))+96*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.),gsl_complex_mul(trH1,trL0L2L1)))-32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L2L4L5))+32*dim*GSL_REAL(trL3L3L4L4)+64*GSL_REAL(gsl_complex_mul(trL0L5,trL1L4))+32*dim*GSL_REAL(trL0L0L2L2)+96*GSL_REAL(gsl_complex_mul(trL2L4,trL2L4))+16*dim*GSL_REAL(trL0L3L0L3)+16*GSL_REAL(gsl_complex_mul(trH0H0,trL0L0))-32*dim*GSL_REAL(trL0L5L4L1)-32*dim*GSL_REAL(trH0L5H1L0)+32*dim*GSL_REAL(trH0H0L0L0)+48*GSL_REAL(gsl_complex_mul(trL1L1,trL3L3))-32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L4L3L5))+32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L5L1L2))-32*dim*GSL_REAL(trH0L3L2H1)+16*GSL_REAL(gsl_complex_mul(trL0L0,trL5L5))+16*dim*GSL_REAL(trH1L0H1L0)+32*dim*GSL_REAL(trL1L3L2L4)+32*GSL_REAL(gsl_complex_mul(trL3L4,trL3L4))+32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L0L2L4))+64*GSL_REAL(gsl_complex_mul(trH0L2,trH1L3))+16*dim*GSL_REAL(trL0L4L0L4)+32*GSL_REAL(gsl_complex_mul(trH0,trH0L0L0))+8*dim*GSL_REAL(trH1H1H1H1)+16*GSL_REAL(gsl_complex_mul(trH0H0,trH1H1))-96*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.),gsl_complex_mul(trH1,trL0L1L2)))+64*GSL_REAL(gsl_complex_mul(trH0H1,trL1L4))+32*dim*GSL_REAL(trH1H1L5L5)-32*GSL_REAL(gsl_complex_mul(trH0L2L3,trH1))-64*GSL_REAL(gsl_complex_mul(trL0L3,trL2L5))+32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L2L1L0))+24*GSL_REAL(gsl_complex_mul(trL3L3,trL3L3))+96*GSL_REAL(gsl_complex_mul(trH1,trH1L1L1))-32*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.),gsl_complex_mul(trH1,trL0L3L4)))+96*GSL_REAL(gsl_complex_mul(trH0,trH0L5L5))-16*dim*GSL_REAL(trL3L4L3L4)+32*GSL_REAL(gsl_complex_mul(trL0L1,trL0L1))-32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L5L2L1))+32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L0L4L2))-96*GSL_REAL(gsl_complex_mul(trH1L0,trH1L0))+32*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.),gsl_complex_mul(trH1,trL0L4L3)))-32*GSL_REAL(gsl_complex_mul(trH0L2,trH0L2))+32*dim*GSL_REAL(trL0L4L1L5)+32*GSL_REAL(gsl_complex_mul(trL1L2,trL1L2))+32*dim*GSL_REAL(trL1L1L4L4)+64*GSL_REAL(gsl_complex_mul(trL0L1,trL4L5))+32*GSL_REAL(gsl_complex_mul(trH1,trH1H1H1))+32*GSL_REAL(gsl_complex_mul(trH0,trH0L1L1))+8*dim*GSL_REAL(trL0L0L0L0)+32*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.),gsl_complex_mul(trH1,trL2L5L4)))-32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L2L0L4))+32*GSL_REAL(gsl_complex_mul(trH1,trH1L4L4))+32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L5L3L1))-32*GSL_REAL(gsl_complex_mul(trH0L1,trH0L1))+32*dim*GSL_REAL(trL1L1L5L5)-32*dim*GSL_REAL(trH0L5L0H1)-32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L3L5L1))-16*dim*GSL_REAL(trL2L3L2L3)+32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L4L0L3))+48*GSL_REAL(gsl_complex_mul(trH0H0,trL5L5))-16*dim*GSL_REAL(trH0L0H0L0)-96*GSL_REAL(gsl_complex_mul(trH0L3,trH0L3))+16*GSL_REAL(gsl_complex_mul(trL1L1,trL4L4))+32*dim*GSL_REAL(trL0L1L5L4)-16*dim*GSL_REAL(trH0L1H0L1)+32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L3L4L5))+32*GSL_REAL(gsl_complex_mul(trH0,trH0H1H1))+32*dim*GSL_REAL(trL1L1L3L3)+32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L4L5L3))+64*GSL_REAL(gsl_complex_mul(trL1L3,trL2L4))+32*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.),gsl_complex_mul(trH0,trL0L1L3)))+32*dim*GSL_REAL(trH0L1H1L4)-32*GSL_REAL(gsl_complex_mul(trH0L0,trH0L0))-32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L3L5L4))-32*dim*GSL_REAL(trH0H1L4L1)+48*GSL_REAL(gsl_complex_mul(trH1H1,trL2L2))+32*dim*GSL_REAL(trH1H1L3L3)-32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L3L4L0))+32*dim*GSL_REAL(trL0L0L3L3)+32*dim*GSL_REAL(trL1L4L2L3)+32*GSL_REAL(gsl_complex_mul(trL4L5,trL4L5))+32*dim*GSL_REAL(trH0H0L5L5)+16*dim*GSL_REAL(trH0L5H0L5)+32*GSL_REAL(gsl_complex_mul(trH0H0H1,trH1))+32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L0L4L3))-32*dim*GSL_REAL(trL0L1L4L5)-64*GSL_REAL(gsl_complex_mul(trH0H1,trL2L3))+32*GSL_REAL(gsl_complex_mul(trH0,trH1L4L1))+64*GSL_REAL(gsl_complex_mul(trH0L5,trH1L0))-16*dim*GSL_REAL(trL0L2L0L2)-96*GSL_REAL(gsl_complex_mul(trH1L1,trH1L1))+16*dim*GSL_REAL(trH0L3H0L3)+96*GSL_REAL(gsl_complex_mul(trH1,trH1L2L2))+32*dim*GSL_REAL(trH0H1L5L0)+48*GSL_REAL(gsl_complex_mul(trL1L1,trL5L5))+32*dim*GSL_REAL(trL1L2L4L3)+32*dim*GSL_REAL(trL1L1L2L2)+16*dim*GSL_REAL(trL1L3L1L3)+32*GSL_REAL(gsl_complex_mul(trH0H1,trH0H1))-32*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.),gsl_complex_mul(trH1,trL2L4L5)))+8*dim*GSL_REAL(trL1L1L1L1)-32*GSL_REAL(gsl_complex_mul(trH0,trH1L5L0))+24*GSL_REAL(gsl_complex_mul(trL1L1,trL1L1))+16*GSL_REAL(gsl_complex_mul(trL2L2,trL3L3))-32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L2L5L1))-32*dim*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L3L1L0))-32*GSL_REAL(gsl_complex_mul(gsl_complex_rect(0., 1.),gsl_complex_mul(trH0,trL1L5L2)))-16*dim*GSL_REAL(trH1L4H1L4)-32*GSL_REAL(gsl_complex_mul(trH0L0L5,trH1));
    if(control[1])
        vecS[1] = G*(+8*dim*GSL_IMAG(trH1H1)+8*dim*GSL_IMAG(trL1L1)+8*GSL_IMAG(gsl_complex_mul(trH0,trH0))+8*dim*GSL_IMAG(trL2L2)+8*dim*GSL_IMAG(trL5L5)+8*GSL_IMAG(gsl_complex_mul(trH1,trH1))+8*dim*GSL_IMAG(trL0L0)+8*dim*GSL_IMAG(trL4L4)+8*dim*GSL_IMAG(trL3L3)+8*dim*GSL_IMAG(trH0H0)) +96*GSL_IMAG(gsl_complex_mul(trH0,trH0L3L3))+32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L4L0L2))+32*GSL_IMAG(gsl_complex_mul(trL3L5,trL3L5))-16*dim*GSL_IMAG(trH0H1H0H1)+16*GSL_IMAG(gsl_complex_mul(trH1H1,trL3L3))+32*GSL_IMAG(gsl_complex_mul(trH0,trH1L1L4))+32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L0L3L1))+32*GSL_IMAG(gsl_complex_mul(trH0L4L1,trH1))-64*GSL_IMAG(gsl_complex_mul(trL0L5,trL2L3))-32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L3L0L4))+16*GSL_IMAG(gsl_complex_mul(trL3L3,trL4L4))+96*GSL_IMAG(gsl_complex_mul(trH0,trH0L4L4))+8*dim*GSL_IMAG(trL5L5L5L5)-32*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.),gsl_complex_mul(trH0,trL0L3L1)))-32*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.),gsl_complex_mul(trH0,trL0L4L2)))+48*GSL_IMAG(gsl_complex_mul(trH0H0,trL3L3))+32*dim*GSL_IMAG(trH0L2L3H1)+16*GSL_IMAG(gsl_complex_mul(trH1H1,trL5L5))+16*GSL_IMAG(gsl_complex_mul(trL4L4,trL5L5))-32*dim*GSL_IMAG(trH0L3H1L2)+32*GSL_IMAG(gsl_complex_mul(trL0L2,trL0L2))+64*GSL_IMAG(gsl_complex_mul(trL0L4,trL1L5))-32*dim*GSL_IMAG(trL1L2L3L4)+16*GSL_IMAG(gsl_complex_mul(trH0H0,trL1L1))+96*GSL_IMAG(gsl_complex_mul(trL0L4,trL0L4))-32*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.),gsl_complex_mul(trH1,trL1L3L5)))+32*dim*GSL_IMAG(trL2L2L4L4)-32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L4L5L2))+32*dim*GSL_IMAG(trH1H1L4L4)+16*GSL_IMAG(gsl_complex_mul(trL0L0,trL1L1))+32*dim*GSL_IMAG(trH1H1L2L2)+48*GSL_IMAG(gsl_complex_mul(trH0H0,trL4L4))+32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L0L2L1))+16*GSL_IMAG(gsl_complex_mul(trH1H1,trL4L4))-16*dim*GSL_IMAG(trL4L5L4L5)+24*GSL_IMAG(gsl_complex_mul(trL0L0,trL0L0))+32*dim*GSL_IMAG(trH0H0L3L3)+32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L5L3L4))+32*dim*GSL_IMAG(trL0L4L5L1)-96*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.),gsl_complex_mul(trH0,trL3L5L4)))+8*dim*GSL_IMAG(trL4L4L4L4)+16*GSL_IMAG(gsl_complex_mul(trH0H0,trL2L2))-32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L0L3L4))+64*GSL_IMAG(gsl_complex_mul(trL1L4,trL2L3))-64*GSL_IMAG(gsl_complex_mul(trL0L2,trL3L5))+32*dim*GSL_IMAG(trH0L4L1H1)+32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L4L3L0))+24*GSL_IMAG(gsl_complex_mul(trL2L2,trL2L2))+32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L2L5L4))-16*dim*GSL_IMAG(trH0L2H0L2)+32*dim*GSL_IMAG(trH0L0L5H1)-32*dim*GSL_IMAG(trL0L2L5L3)-32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L1L3L5))-32*GSL_IMAG(gsl_complex_mul(trH0,trH1L3L2))-32*dim*GSL_IMAG(trH0H1L0L5)+32*dim*GSL_IMAG(trL4L4L5L5)-32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L4L2L0))-32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L1L2L0))+32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L1L5L3))+64*GSL_IMAG(gsl_complex_mul(trH0L0,trH1L5))+32*GSL_IMAG(gsl_complex_mul(trH1,trH1L5L5))-32*GSL_IMAG(gsl_complex_mul(trH0L3L2,trH1))-32*GSL_IMAG(gsl_complex_mul(trH0L5L0,trH1))+32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L5L4L2))-32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L3L1L5))-32*GSL_IMAG(gsl_complex_mul(trH1L3,trH1L3))+24*GSL_IMAG(gsl_complex_mul(trH1H1,trH1H1))-32*dim*GSL_IMAG(trL1L4L3L2)+48*GSL_IMAG(gsl_complex_mul(trL2L2,trL4L4))-32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L4L2L5))+32*GSL_IMAG(gsl_complex_mul(trH1,trH1L3L3))+96*GSL_IMAG(gsl_complex_mul(trL0L3,trL0L3))-64*GSL_IMAG(gsl_complex_mul(trH0L4,trH1L1))+32*dim*GSL_IMAG(trH1H1L0L0)+48*GSL_IMAG(gsl_complex_mul(trH1H1,trL1L1))+48*GSL_IMAG(gsl_complex_mul(trL0L0,trL4L4))+16*dim*GSL_IMAG(trH1L2H1L2)-32*GSL_IMAG(gsl_complex_mul(trH1L4,trH1L4))+24*GSL_IMAG(gsl_complex_mul(trL5L5,trL5L5))-16*dim*GSL_IMAG(trL0L1L0L1)+64*GSL_IMAG(gsl_complex_mul(trH0L3,trH1L2))-32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L5L4L3))+32*dim*GSL_IMAG(trL0L2L3L5)-32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L2L4L0))+32*dim*GSL_IMAG(trH0H1L3L2)+24*GSL_IMAG(gsl_complex_mul(trL4L4,trL4L4))+48*GSL_IMAG(gsl_complex_mul(trL2L2,trL5L5))-32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L0L1L2))+32*dim*GSL_IMAG(trL2L2L3L3)-32*GSL_IMAG(gsl_complex_mul(trH0,trH1L2L3))+32*dim*GSL_IMAG(trL0L5L1L4)+8*dim*GSL_IMAG(trH0H0H0H0)+16*dim*GSL_IMAG(trL2L4L2L4)+96*GSL_IMAG(gsl_complex_mul(trH1,trH1L0L0))+32*dim*GSL_IMAG(trH0H0L2L2)+24*GSL_IMAG(gsl_complex_mul(trH0H0,trH0H0))+96*GSL_IMAG(gsl_complex_mul(trL1L5,trL1L5))+16*dim*GSL_IMAG(trH1L1H1L1)+8*dim*GSL_IMAG(trL3L3L3L3)+32*GSL_IMAG(gsl_complex_mul(trL0L5,trL0L5))+32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L3L0L1))-64*GSL_IMAG(gsl_complex_mul(trH0L1,trH1L4))+32*dim*GSL_IMAG(trL0L0L1L1)+32*dim*GSL_IMAG(trL0L0L5L5)+32*dim*GSL_IMAG(trL3L3L5L5)-32*GSL_IMAG(gsl_complex_mul(trH1L5,trH1L5))+48*GSL_IMAG(gsl_complex_mul(trH1H1,trL0L0))+96*GSL_IMAG(gsl_complex_mul(trL1L3,trL1L3))-32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L1L3L0))-32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L1L0L3))-32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L2L0L1))-16*dim*GSL_IMAG(trL0L5L0L5)-32*GSL_IMAG(gsl_complex_mul(trH0,trH1L0L5))+32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L1L5L2))+32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L5L1L3))+32*GSL_IMAG(gsl_complex_mul(trH0,trH0H0H0))-32*dim*GSL_IMAG(trH0L1L4H1)+32*GSL_IMAG(gsl_complex_mul(trL2L3,trL2L3))-64*GSL_IMAG(gsl_complex_mul(trH0H1,trL0L5))-32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L2L1L5))+32*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.),gsl_complex_mul(trH0,trL1L2L5)))-16*dim*GSL_IMAG(trL1L4L1L4)+32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L1L2L5))+16*dim*GSL_IMAG(trL1L5L1L5)-96*GSL_IMAG(gsl_complex_mul(trH1L2,trH1L2))+32*dim*GSL_IMAG(trH0H1L1L4)-16*dim*GSL_IMAG(trH1L5H1L5)+32*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.),gsl_complex_mul(trH1,trL1L5L3)))+96*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.),gsl_complex_mul(trH0,trL3L4L5)))+32*dim*GSL_IMAG(trH1H1L1L1)+64*GSL_IMAG(gsl_complex_mul(trL1L2,trL3L4))+8*dim*GSL_IMAG(trL2L2L2L2)+32*dim*GSL_IMAG(trH0H0L4L4)+16*GSL_IMAG(gsl_complex_mul(trL3L3,trL5L5))+96*GSL_IMAG(gsl_complex_mul(trL2L5,trL2L5))+32*dim*GSL_IMAG(trH0H0H1H1)+32*dim*GSL_IMAG(trL2L2L5L5)+32*dim*GSL_IMAG(trH0H0L1L1)+16*dim*GSL_IMAG(trL2L5L2L5)-16*dim*GSL_IMAG(trH1L3H1L3)+32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L1L0L2))+32*GSL_IMAG(gsl_complex_mul(trH0L1L4,trH1))+16*GSL_IMAG(gsl_complex_mul(trL1L1,trL2L2))-32*dim*GSL_IMAG(trH0L0H1L5)-32*dim*GSL_IMAG(trL0L3L2L5)+32*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.),gsl_complex_mul(trH0,trL0L2L4)))+32*dim*GSL_IMAG(trL1L3L4L2)+32*GSL_IMAG(gsl_complex_mul(trH0,trH0L2L2))+32*dim*GSL_IMAG(trH0L4H1L1)+16*GSL_IMAG(gsl_complex_mul(trL0L0,trL2L2))-96*GSL_IMAG(gsl_complex_mul(trH0L4,trH0L4))-96*GSL_IMAG(gsl_complex_mul(trH0L5,trH0L5))-32*dim*GSL_IMAG(trL0L3L5L2)-32*dim*GSL_IMAG(trL0L5L2L3)-32*dim*GSL_IMAG(trH0L2H1L3)+32*dim*GSL_IMAG(trL0L5L3L2)+32*GSL_IMAG(gsl_complex_mul(trL1L4,trL1L4))-16*dim*GSL_IMAG(trL1L2L1L2)+32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L5L2L4))+16*dim*GSL_IMAG(trH0L4H0L4)+32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L0L1L3))-32*dim*GSL_IMAG(trH0H1L2L3)+32*dim*GSL_IMAG(trL0L0L4L4)-16*dim*GSL_IMAG(trL3L5L3L5)+48*GSL_IMAG(gsl_complex_mul(trL0L0,trL3L3))+96*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.),gsl_complex_mul(trH1,trL0L2L1)))-32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L2L4L5))+32*dim*GSL_IMAG(trL3L3L4L4)+64*GSL_IMAG(gsl_complex_mul(trL0L5,trL1L4))+32*dim*GSL_IMAG(trL0L0L2L2)+96*GSL_IMAG(gsl_complex_mul(trL2L4,trL2L4))+16*dim*GSL_IMAG(trL0L3L0L3)+16*GSL_IMAG(gsl_complex_mul(trH0H0,trL0L0))-32*dim*GSL_IMAG(trL0L5L4L1)-32*dim*GSL_IMAG(trH0L5H1L0)+32*dim*GSL_IMAG(trH0H0L0L0)+48*GSL_IMAG(gsl_complex_mul(trL1L1,trL3L3))-32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L4L3L5))+32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L5L1L2))-32*dim*GSL_IMAG(trH0L3L2H1)+16*GSL_IMAG(gsl_complex_mul(trL0L0,trL5L5))+16*dim*GSL_IMAG(trH1L0H1L0)+32*dim*GSL_IMAG(trL1L3L2L4)+32*GSL_IMAG(gsl_complex_mul(trL3L4,trL3L4))+32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L0L2L4))+64*GSL_IMAG(gsl_complex_mul(trH0L2,trH1L3))+16*dim*GSL_IMAG(trL0L4L0L4)+32*GSL_IMAG(gsl_complex_mul(trH0,trH0L0L0))+8*dim*GSL_IMAG(trH1H1H1H1)+16*GSL_IMAG(gsl_complex_mul(trH0H0,trH1H1))-96*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.),gsl_complex_mul(trH1,trL0L1L2)))+64*GSL_IMAG(gsl_complex_mul(trH0H1,trL1L4))+32*dim*GSL_IMAG(trH1H1L5L5)-32*GSL_IMAG(gsl_complex_mul(trH0L2L3,trH1))-64*GSL_IMAG(gsl_complex_mul(trL0L3,trL2L5))+32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L2L1L0))+24*GSL_IMAG(gsl_complex_mul(trL3L3,trL3L3))+96*GSL_IMAG(gsl_complex_mul(trH1,trH1L1L1))-32*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.),gsl_complex_mul(trH1,trL0L3L4)))+96*GSL_IMAG(gsl_complex_mul(trH0,trH0L5L5))-16*dim*GSL_IMAG(trL3L4L3L4)+32*GSL_IMAG(gsl_complex_mul(trL0L1,trL0L1))-32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L5L2L1))+32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L0L4L2))-96*GSL_IMAG(gsl_complex_mul(trH1L0,trH1L0))+32*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.),gsl_complex_mul(trH1,trL0L4L3)))-32*GSL_IMAG(gsl_complex_mul(trH0L2,trH0L2))+32*dim*GSL_IMAG(trL0L4L1L5)+32*GSL_IMAG(gsl_complex_mul(trL1L2,trL1L2))+32*dim*GSL_IMAG(trL1L1L4L4)+64*GSL_IMAG(gsl_complex_mul(trL0L1,trL4L5))+32*GSL_IMAG(gsl_complex_mul(trH1,trH1H1H1))+32*GSL_IMAG(gsl_complex_mul(trH0,trH0L1L1))+8*dim*GSL_IMAG(trL0L0L0L0)+32*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.),gsl_complex_mul(trH1,trL2L5L4)))-32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L2L0L4))+32*GSL_IMAG(gsl_complex_mul(trH1,trH1L4L4))+32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L5L3L1))-32*GSL_IMAG(gsl_complex_mul(trH0L1,trH0L1))+32*dim*GSL_IMAG(trL1L1L5L5)-32*dim*GSL_IMAG(trH0L5L0H1)-32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L3L5L1))-16*dim*GSL_IMAG(trL2L3L2L3)+32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L4L0L3))+48*GSL_IMAG(gsl_complex_mul(trH0H0,trL5L5))-16*dim*GSL_IMAG(trH0L0H0L0)-96*GSL_IMAG(gsl_complex_mul(trH0L3,trH0L3))+16*GSL_IMAG(gsl_complex_mul(trL1L1,trL4L4))+32*dim*GSL_IMAG(trL0L1L5L4)-16*dim*GSL_IMAG(trH0L1H0L1)+32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L3L4L5))+32*GSL_IMAG(gsl_complex_mul(trH0,trH0H1H1))+32*dim*GSL_IMAG(trL1L1L3L3)+32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L4L5L3))+64*GSL_IMAG(gsl_complex_mul(trL1L3,trL2L4))+32*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.),gsl_complex_mul(trH0,trL0L1L3)))+32*dim*GSL_IMAG(trH0L1H1L4)-32*GSL_IMAG(gsl_complex_mul(trH0L0,trH0L0))-32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L3L5L4))-32*dim*GSL_IMAG(trH0H1L4L1)+48*GSL_IMAG(gsl_complex_mul(trH1H1,trL2L2))+32*dim*GSL_IMAG(trH1H1L3L3)-32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L3L4L0))+32*dim*GSL_IMAG(trL0L0L3L3)+32*dim*GSL_IMAG(trL1L4L2L3)+32*GSL_IMAG(gsl_complex_mul(trL4L5,trL4L5))+32*dim*GSL_IMAG(trH0H0L5L5)+16*dim*GSL_IMAG(trH0L5H0L5)+32*GSL_IMAG(gsl_complex_mul(trH0H0H1,trH1))+32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH1L0L4L3))-32*dim*GSL_IMAG(trL0L1L4L5)-64*GSL_IMAG(gsl_complex_mul(trH0H1,trL2L3))+32*GSL_IMAG(gsl_complex_mul(trH0,trH1L4L1))+64*GSL_IMAG(gsl_complex_mul(trH0L5,trH1L0))-16*dim*GSL_IMAG(trL0L2L0L2)-96*GSL_IMAG(gsl_complex_mul(trH1L1,trH1L1))+16*dim*GSL_IMAG(trH0L3H0L3)+96*GSL_IMAG(gsl_complex_mul(trH1,trH1L2L2))+32*dim*GSL_IMAG(trH0H1L5L0)+48*GSL_IMAG(gsl_complex_mul(trL1L1,trL5L5))+32*dim*GSL_IMAG(trL1L2L4L3)+32*dim*GSL_IMAG(trL1L1L2L2)+16*dim*GSL_IMAG(trL1L3L1L3)+32*GSL_IMAG(gsl_complex_mul(trH0H1,trH0H1))-32*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.),gsl_complex_mul(trH1,trL2L4L5)))+8*dim*GSL_IMAG(trL1L1L1L1)-32*GSL_IMAG(gsl_complex_mul(trH0,trH1L5L0))+24*GSL_IMAG(gsl_complex_mul(trL1L1,trL1L1))+16*GSL_IMAG(gsl_complex_mul(trL2L2,trL3L3))-32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L2L5L1))-32*dim*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.), trH0L3L1L0))-32*GSL_IMAG(gsl_complex_mul(gsl_complex_rect(0., 1.),gsl_complex_mul(trH0,trL1L5L2)))-16*dim*GSL_IMAG(trH1L4H1L4)-32*GSL_IMAG(gsl_complex_mul(trH0L0L5,trH1));
    if(control[2])
        vecS[2] = GSL_REAL(trH0);
    if(control[3])
        vecS[3] = GSL_REAL(trH0H0);
    if(control[4])
        vecS[4] = GSL_REAL(trH1);
    if(control[5])
        vecS[5] = GSL_REAL(trH1H1);
}
